package com.blsd.titan

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.animation.*
import androidx.compose.animation.core.*
import androidx.compose.foundation.clickable
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.layout.ContentScale

class MainActivity:ComponentActivity(){
 override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);setContent{TitanTheme{TitanApp()}}}
}
private enum class Screen{WELCOME,OBJECTIVE,PROFILE,PROFESSION,WORK,WORK_DETAIL,TRAINING,MEAL_COUNT,MAINTENANCE,STRATEGY,TODAY,MEALS,DISH,ALTERNATIVES,INGREDIENT,DAY_CLOSE,WEEK,WEEK_REVIEW,BODY,ADD,SOCIAL}

@Composable fun TitanApp(){
 val context=LocalContext.current
 val store=remember{TitanStore(context)}
 val saved=remember{runCatching{store.load()}.getOrNull()}
 var screen by remember{mutableStateOf(Screen.WELCOME)}
 var sex by remember{mutableStateOf(saved?.sex?:Sex.MALE)}
 var age by remember{mutableStateOf((saved?.age?:39).toString())};var height by remember{mutableStateOf((saved?.heightCm?:170.0).toInt().toString())};var weight by remember{mutableStateOf((saved?.weightKg?:93.0).toInt().toString())}
 var profession by remember{mutableStateOf(TITAN_PROFESSIONS.first())}
 var standing by remember{mutableStateOf("7")};var moving by remember{mutableStateOf("5")};var load by remember{mutableStateOf("2")};var breaks by remember{mutableStateOf("1")};var workIntensity by remember{mutableStateOf(WorkIntensity.MODERATE)};var variableDay by remember{mutableStateOf(true)}
 var sessions by remember{mutableStateOf("4")};var minutes by remember{mutableStateOf("75")};var trainingIntensity by remember{mutableStateOf(TrainingIntensity.HIGH)};var mealCount by remember{mutableStateOf(saved?.mealCount?:4)}
 var estimate by remember{mutableStateOf<EnergyEstimate?>(saved?.let{EnergyEstimate(0,0,0,0,it.maintenance)})};var strategy by remember{mutableStateOf(saved?.strategy?:Strategy.MODERATE)}
 var selectedMealId by remember{mutableStateOf<String?>(null)};var proposedDish by remember{mutableStateOf<Dish?>(null)};var selectedIngredient by remember{mutableStateOf(0)}
 var meals by remember{mutableStateOf(saved?.let{
  runCatching{
   val base=TitanEngine.plans(it.maintenance).first{p->p.strategy==it.strategy}
   store.ensureToday(base.copy(target=store.activeTarget(base.target))).meals
  }.getOrElse{
   store.clear()
   emptyList()
  }
 }?:emptyList())}
 fun currentPlan():CaloriePlan{val m=estimate?.maintenance?:1;val base=TitanEngine.plans(m).first{it.strategy==strategy};val target=store.activeTarget(base.target);return base.copy(target=target)}
 Surface(Modifier.fillMaxSize(),color=TitanBackground){
  Box(Modifier.fillMaxSize().background(Brush.verticalGradient(listOf(TitanBackground,Color(0xFF0C1821),TitanBackground)))){
  AnimatedContent(targetState=screen,transitionSpec={fadeIn(tween(260))+slideInHorizontally(tween(260)){it/10} togetherWith fadeOut(tween(180))},label="screen"){shownScreen->
  Box(Modifier.fillMaxSize().windowInsetsPadding(WindowInsets.navigationBars)){TitanAtmosphere();
  when(shownScreen){
   Screen.WELCOME->Welcome{screen=if(saved!=null)Screen.TODAY else Screen.OBJECTIVE}
   Screen.OBJECTIVE->Objective{screen=Screen.PROFILE}
   Screen.PROFILE->Profile(age,{age=it},height,{height=it},weight,{weight=it},sex,{sex=it}){screen=Screen.PROFESSION}
   Screen.PROFESSION->ProfessionQuestion(profession,{profession=it}){screen=Screen.WORK}
   Screen.WORK->Work(standing,{standing=it},moving,{moving=it},load,{load=it}){screen=Screen.WORK_DETAIL}
   Screen.WORK_DETAIL->WorkDetail(breaks,{breaks=it},workIntensity,{workIntensity=it},variableDay,{variableDay=it}){screen=Screen.TRAINING}
   Screen.TRAINING->Training(sessions,{sessions=it},minutes,{minutes=it},trainingIntensity,{trainingIntensity=it}){
    val w=weight.toDoubleOrNull()?:70.0
    val qe=QuestionnaireEngine.energy(w,ActivityQuestionnaire(standing.toDoubleOrNull()?:0.0,moving.toDoubleOrNull()?:0.0,load.toDoubleOrNull()?:0.0,workIntensity,breaks.toDoubleOrNull()?:0.0,variableDay,profession),TrainingQuestionnaire(sessions.toIntOrNull()?:0,minutes.toIntOrNull()?:0,trainingIntensity))
    estimate=TitanEngine.estimateEnergy(UserProfile(sex,age.toIntOrNull()?:30,height.toDoubleOrNull()?:170.0,w,1.2,qe.workDailyKcal,qe.trainingDailyKcal));screen=Screen.MEAL_COUNT
   }
   Screen.MEAL_COUNT->MealCountQuestion(mealCount,{mealCount=it}){screen=Screen.MAINTENANCE}
   Screen.MAINTENANCE->Maintenance(estimate!!){screen=Screen.STRATEGY}
   Screen.STRATEGY->Strategies(estimate!!.maintenance,strategy,{strategy=it}){
    val profile=UserProfile(sex,age.toIntOrNull()?:30,height.toDoubleOrNull()?:170.0,weight.toDoubleOrNull()?:70.0)
    store.save(profile,estimate!!.maintenance,strategy,mealCount)
    val names=mealNamesForCount(mealCount);meals=TitanEngine.distribute(currentPlan().target,names);store.saveDay(meals,currentPlan());screen=Screen.TODAY}
   Screen.TODAY->{val p=currentPlan();Today(p,TitanEngine.balance(p,meals.sumOf{it.consumedKcal}),MealEngine.macroBalance(MealEngine.macroTarget(weight.toDoubleOrNull()?:70.0,p.target),meals),meals,{screen=Screen.MEALS},{id->val updated=meals.map{if(it.id==id)it.copy(status=MealStatus.SKIPPED)else it}.let(TitanEngine::redistribute);meals=updated;store.saveDay(updated,p)},{screen=Screen.DAY_CLOSE},{screen=Screen.WEEK},{screen=Screen.ADD},{screen=Screen.SOCIAL})}
   Screen.MEALS->MealList(meals,{m->selectedMealId=m.id;proposedDish=MealEngine.propose(m.plannedKcal);screen=Screen.DISH},{id->val updated=meals.map{if(it.id==id)it.copy(status=MealStatus.SKIPPED)else it}.let(TitanEngine::redistribute);meals=updated;store.saveDay(updated,currentPlan())},{screen=Screen.TODAY})
   Screen.DISH->DishProposal(proposedDish!!,{screen=Screen.ALTERNATIVES},{index->selectedIngredient=index;screen=Screen.INGREDIENT},{
    val id=selectedMealId;val d=proposedDish!!;val updated=meals.map{if(it.id==id)it.copy(name=d.name,consumedKcal=d.kcal,status=MealStatus.CONFIRMED,proteinG=d.proteinG,carbsG=d.carbsG,fatG=d.fatG)else it}.let(TitanEngine::redistribute);meals=updated;store.saveDay(updated,currentPlan());screen=Screen.MEALS
   },{screen=Screen.MEALS})
   Screen.ALTERNATIVES->Alternatives(meals.first{it.id==selectedMealId}.plannedKcal,proposedDish!!,{d->proposedDish=d;screen=Screen.DISH},{screen=Screen.DISH})
   Screen.INGREDIENT->IngredientEditor(proposedDish!!,selectedIngredient,{g->proposedDish=MealEngine.resizeIngredient(proposedDish!!,selectedIngredient,g)},{replacement->proposedDish=MealEngine.replaceIngredient(proposedDish!!,selectedIngredient,replacement);screen=Screen.DISH},{screen=Screen.DISH})
   Screen.DAY_CLOSE->DayClose(TitanEngine.closeDay(currentPlan(),meals),store.remainingDaysInWeek()){store.saveDay(meals,currentPlan(),closed=true);screen=Screen.WEEK}
   Screen.WEEK->WeekHistory(store.weekHistory(),{screen=Screen.WEEK_REVIEW},{screen=Screen.BODY}){screen=Screen.TODAY}
   Screen.BODY->BodyProgress(store.bodyHistory(),{w,waist->store.saveBodyEntry(w,waist)},{screen=Screen.TODAY})
   Screen.WEEK_REVIEW->WeeklyReviewScreen(store.weekHistory(),currentPlan().target,{adjustment->store.applyWeeklyAdjustment(adjustment);val names=mealNamesForCount(mealCount);meals=TitanEngine.distribute(adjustment.nextTarget,names);store.saveDay(meals,currentPlan());screen=Screen.TODAY},{screen=Screen.TODAY})
   Screen.SOCIAL->SocialMealScreen({name,kcal->val updated=meals+MealSlot("social-"+System.currentTimeMillis(),name,kcal,kcal,MealStatus.CONFIRMED);meals=updated;store.saveDay(updated,currentPlan());screen=Screen.TODAY},{screen=Screen.TODAY})
   Screen.ADD->AddMeal({n,k->val i=meals.indexOfFirst{it.status==MealStatus.PENDING};if(i>=0){val updated=meals.mapIndexed{x,m->if(x==i)m.copy(name=n,consumedKcal=k,status=MealStatus.CONFIRMED)else m}.let(TitanEngine::redistribute);meals=updated;store.saveDay(updated,currentPlan())};screen=Screen.TODAY}){screen=Screen.TODAY}
  }
  if(shownScreen!=Screen.WELCOME){TitanArrows(shownScreen,{screen=previousScreen(shownScreen)},{screen=nextScreen(shownScreen)})}
  }}
  }
 }
}
private fun previousScreen(s:Screen)=when(s){Screen.OBJECTIVE->Screen.WELCOME;Screen.PROFILE->Screen.OBJECTIVE;Screen.PROFESSION->Screen.PROFILE;Screen.WORK->Screen.PROFESSION;Screen.WORK_DETAIL->Screen.WORK;Screen.TRAINING->Screen.WORK_DETAIL;Screen.MEAL_COUNT->Screen.TRAINING;Screen.MAINTENANCE->Screen.MEAL_COUNT;Screen.STRATEGY->Screen.MAINTENANCE;Screen.TODAY->Screen.TODAY;Screen.MEALS->Screen.TODAY;Screen.DISH->Screen.MEALS;Screen.ALTERNATIVES->Screen.DISH;Screen.INGREDIENT->Screen.DISH;Screen.DAY_CLOSE->Screen.TODAY;Screen.WEEK->Screen.TODAY;Screen.WEEK_REVIEW->Screen.WEEK;Screen.BODY->Screen.WEEK;Screen.ADD->Screen.TODAY;Screen.SOCIAL->Screen.ADD;else->s}
private fun nextScreen(s:Screen)=when(s){Screen.TODAY->Screen.MEALS;Screen.MEALS->Screen.ADD;Screen.ADD->Screen.SOCIAL;Screen.WEEK->Screen.BODY;else->s}
@Composable private fun TitanArrows(s:Screen,back:()->Unit,next:()->Unit){Row(Modifier.fillMaxWidth().padding(horizontal=18.dp,vertical=12.dp),horizontalArrangement=Arrangement.SpaceBetween){Text("‹",fontSize=38.sp,color=TitanText,modifier=Modifier.clickable{back()}.padding(8.dp));val n=nextScreen(s);Text("›",fontSize=38.sp,color=if(n!=s)TitanPrimary else TitanDivider,modifier=Modifier.clickable(enabled=n!=s){next()}.padding(8.dp))}}
@Composable private fun TitanAtmosphere(){Canvas(Modifier.fillMaxSize()){val h=size.height;val w=size.width;drawCircle(Color(0x162ED4B7),w*.72f,Offset(w*.88f,h*.10f));drawCircle(Color(0x0D57C7E6),w*.92f,Offset(w*.08f,h*.55f));val far=Path().apply{moveTo(0f,h*.88f);lineTo(w*.17f,h*.77f);lineTo(w*.31f,h*.86f);lineTo(w*.52f,h*.69f);lineTo(w*.72f,h*.84f);lineTo(w*.90f,h*.73f);lineTo(w,h*.80f);lineTo(w,h);lineTo(0f,h);close()};drawPath(far,Color(0x152A3943));val near=Path().apply{moveTo(0f,h*.94f);lineTo(w*.22f,h*.82f);lineTo(w*.38f,h*.91f);lineTo(w*.61f,h*.76f);lineTo(w*.79f,h*.89f);lineTo(w,h*.81f);lineTo(w,h);lineTo(0f,h);close()};drawPath(near,Color(0x24202D35));drawLine(TitanPrimary.copy(alpha=.12f),Offset(w*.52f,h*.69f),Offset(w*.61f,h*.76f),2f)}}
@Composable private fun TitanMark(){Image(painter=painterResource(R.drawable.titan_mark_official),contentDescription="TITÁN",modifier=Modifier.width(154.dp).height(100.dp),contentScale=ContentScale.Fit)}
@Composable private fun FoodVisual(modifier:Modifier=Modifier){Canvas(modifier.clip(RoundedCornerShape(18.dp)).background(Brush.linearGradient(listOf(Color(0xFF25323A),Color(0xFF0D151B))))){val w=size.width;val h=size.height;drawCircle(Color(0xFF11191E),w*.36f,Offset(w*.50f,h*.52f));drawCircle(Color(0xFFD9C49A),w*.26f,Offset(w*.50f,h*.52f));drawCircle(Color(0xFF4CAF7A),w*.11f,Offset(w*.39f,h*.43f));drawCircle(Color(0xFFE6B85C),w*.10f,Offset(w*.60f,h*.43f));drawCircle(Color(0xFFB66D52),w*.11f,Offset(w*.48f,h*.62f));drawCircle(Color(0xFFF1E3C6),w*.08f,Offset(w*.64f,h*.61f));drawCircle(TitanPrimary.copy(alpha=.16f),w*.55f,Offset(w*.5f,h*.5f))}}
@Composable private fun Welcome(next:()->Unit){Box(Modifier.fillMaxSize().clickable{next()}){Image(painter=painterResource(R.drawable.titan_welcome),contentDescription="Bienvenida TITÁN",modifier=Modifier.fillMaxSize(),contentScale=ContentScale.Crop)}}
@Composable private fun Header(step:String,title:String){Spacer(Modifier.height(62.dp));Text(step.uppercase(),color=TitanPrimary,style=MaterialTheme.typography.labelLarge,letterSpacing=1.4.sp);Spacer(Modifier.height(7.dp));Text(title.uppercase(),style=MaterialTheme.typography.headlineLarge);Box(Modifier.padding(top=12.dp,bottom=20.dp).height(2.dp).width(54.dp).background(TitanPrimary))}
@Composable private fun Field(label:String,value:String,set:(String)->Unit){OutlinedTextField(value,{set(it.filter(Char::isDigit))},label={Text(label)},modifier=Modifier.fillMaxWidth().padding(vertical=5.dp),colors=OutlinedTextFieldDefaults.colors(focusedBorderColor=TitanPrimary,unfocusedBorderColor=TitanDivider))}
@Composable private fun TextFieldInput(label:String,value:String,set:(String)->Unit){OutlinedTextField(value,set,label={Text(label)},modifier=Modifier.fillMaxWidth().padding(vertical=5.dp),colors=OutlinedTextFieldDefaults.colors(focusedBorderColor=TitanPrimary,unfocusedBorderColor=TitanDivider))}
@Composable private fun PrimaryButton(label:String,go:()->Unit){Button(go,Modifier.fillMaxWidth().height(56.dp),shape=RoundedCornerShape(16.dp),colors=ButtonDefaults.buttonColors(containerColor=TitanPrimary,contentColor=TitanBackground),elevation=ButtonDefaults.buttonElevation(defaultElevation=7.dp,pressedElevation=2.dp)){Text(label.uppercase(),fontWeight=FontWeight.ExtraBold,letterSpacing=.8.sp)}}
@Composable private fun Objective(next:()->Unit){var selected by remember{mutableStateOf("Recomposición corporal")};val options=listOf("Recomposición corporal" to "Perder grasa y construir una versión más fuerte de ti.","Rendimiento deportivo" to "Alimenta el entrenamiento y mejora tu rendimiento.","Salud y bienestar" to "Construye hábitos sostenibles para sentirte mejor.","Otro objetivo" to "Configura TITÁN alrededor de una prioridad diferente.");Column(Modifier.padding(horizontal=24.dp)){Header("Paso 1 de 8","¿Cuál es tu objetivo principal?");Text("Selecciona el que mejor se adapta a ti en este momento.",color=TitanTextSecondary);Spacer(Modifier.height(14.dp));options.forEach{(title,desc)->Card(onClick={selected=title},modifier=Modifier.fillMaxWidth().padding(vertical=6.dp),shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=if(selected==title)TitanPrimary.copy(alpha=.13f) else TitanCard),border=if(selected==title)androidx.compose.foundation.BorderStroke(1.dp,TitanPrimary) else null){Row(Modifier.padding(17.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(title.uppercase(),fontWeight=FontWeight.ExtraBold);Text(desc,color=TitanTextSecondary,fontSize=12.sp)};Text(if(selected==title)"✓" else "○",color=if(selected==title)TitanPrimary else TitanTextSecondary,fontSize=22.sp)}}};Spacer(Modifier.weight(1f));PrimaryButton("CONTINUAR",next)}}
@Composable private fun Profile(age:String,setAge:(String)->Unit,height:String,setHeight:(String)->Unit,weightValue:String,setWeight:(String)->Unit,sex:Sex,setSex:(Sex)->Unit,next:()->Unit){Column(Modifier.padding(24.dp)){Header("Paso 2 de 8","Tus datos");Row{FilterChip(sex==Sex.MALE,{setSex(Sex.MALE)},{Text("Hombre")});Spacer(Modifier.width(8.dp));FilterChip(sex==Sex.FEMALE,{setSex(Sex.FEMALE)},{Text("Mujer")})};Field("Edad",age,setAge);Field("Altura (cm)",height,setHeight);Field("Peso (kg)",weightValue,setWeight);Spacer(Modifier.weight(1f));PrimaryButton("Continuar",next)}}
@Composable private fun ProfessionQuestion(selected:Profession,setSelected:(Profession)->Unit,next:()->Unit){var open by remember{mutableStateOf(false)};var query by remember{mutableStateOf("")};Column(Modifier.padding(24.dp)){Header("Paso 3 de 8","¿A qué te dedicas?");Text("Selecciona la profesión que más se aproxime a tu trabajo habitual.",color=TitanTextSecondary);Spacer(Modifier.height(16.dp));Card(onClick={open=true},modifier=Modifier.fillMaxWidth(),shape=RoundedCornerShape(18.dp),colors=CardDefaults.cardColors(containerColor=TitanCard)){Row(Modifier.fillMaxWidth().padding(18.dp)){Text(selected.name,Modifier.weight(1f),fontWeight=FontWeight.Bold);Text("⌄",color=TitanPrimary)}};Text("TITÁN cruzará esta referencia con cómo es realmente tu jornada.",color=TitanTextSecondary,fontSize=12.sp,modifier=Modifier.padding(top=10.dp));Spacer(Modifier.weight(1f));PrimaryButton("Continuar",next)};if(open){AlertDialog(onDismissRequest={open=false},title={Text("Buscar profesión")},text={Column{TextFieldInput("Profesión o aproximación",query){query=it};Spacer(Modifier.height(8.dp));val results=TITAN_PROFESSIONS.filter{query.isBlank()||it.name.contains(query,true)}.take(8);if(results.isEmpty())Text("No hay coincidencias. Busca una profesión aproximada.",color=TitanTextSecondary) else results.forEach{p->Surface(shape=RoundedCornerShape(12.dp),color=if(p.id==selected.id)TitanPrimary.copy(alpha=.12f) else Color.Transparent,modifier=Modifier.fillMaxWidth().clickable{setSelected(p);open=false;query=""}){Text(p.name,Modifier.padding(12.dp),fontWeight=if(p.id==selected.id)FontWeight.Bold else FontWeight.Normal)}}}},confirmButton={},dismissButton={TextButton({open=false}){Text("Cerrar")}})}}
@Composable private fun Work(a:String,sa:(String)->Unit,b:String,sb:(String)->Unit,c:String,sc:(String)->Unit,next:()->Unit){Column(Modifier.padding(24.dp)){Header("Paso 4 de 8","Tu actividad diaria");Text("Queremos medir tu día real, no asignarte una etiqueta genérica.",color=TitanTextSecondary);Field("Horas de pie",a,sa);Field("Horas en movimiento",b,sb);Field("Horas con cargas / trabajo físico",c,sc);Spacer(Modifier.weight(1f));PrimaryButton("Continuar",next)}}
@Composable private fun WorkDetail(breaks:String,setBreaks:(String)->Unit,intensity:WorkIntensity,setIntensity:(WorkIntensity)->Unit,variable:Boolean,setVariable:(Boolean)->Unit,next:()->Unit){Column(Modifier.padding(24.dp)){Header("Paso 5 de 8","Cómo es tu jornada");Field("Horas totales de pausas",breaks,setBreaks);Text("Intensidad habitual",color=TitanTextSecondary);Row{WorkIntensity.entries.forEach{v->FilterChip(intensity==v,{setIntensity(v)},{Text(when(v){WorkIntensity.LOW->"Baja";WorkIntensity.MODERATE->"Media";WorkIntensity.HIGH->"Alta"})});Spacer(Modifier.width(6.dp))}};Spacer(Modifier.height(12.dp));Text("¿Tu actividad cambia mucho de un día a otro?",color=TitanTextSecondary);Row{FilterChip(variable,{setVariable(true)},{Text("Sí")});Spacer(Modifier.width(8.dp));FilterChip(!variable,{setVariable(false)},{Text("No")})};Spacer(Modifier.weight(1f));PrimaryButton("Continuar",next)}}
@Composable private fun Training(a:String,sa:(String)->Unit,b:String,sb:(String)->Unit,intensity:TrainingIntensity,setIntensity:(TrainingIntensity)->Unit,next:()->Unit){Column(Modifier.padding(24.dp)){Header("Paso 6 de 8","Tu entrenamiento");Text("Frecuencia, duración e intensidad alimentan la estimación inicial.",color=TitanTextSecondary);Field("Sesiones por semana",a,sa);Field("Minutos por sesión",b,sb);Text("Intensidad habitual",color=TitanTextSecondary);Row{TrainingIntensity.entries.forEach{v->FilterChip(intensity==v,{setIntensity(v)},{Text(when(v){TrainingIntensity.LIGHT->"Suave";TrainingIntensity.MODERATE->"Media";TrainingIntensity.HIGH->"Alta"})});Spacer(Modifier.width(6.dp))}};Spacer(Modifier.weight(1f));PrimaryButton("Calcular mantenimiento",next)}}
private fun mealNamesForCount(count:Int):List<String> = when(count.coerceIn(2,6)){2->listOf("Comida","Cena");3->listOf("Desayuno","Comida","Cena");4->listOf("Desayuno","Comida","Merienda","Cena");5->listOf("Desayuno","Media mañana","Comida","Merienda","Cena");else->listOf("Desayuno","Media mañana","Comida","Merienda","Cena","Recena")}
@Composable private fun MealCountQuestion(count:Int,setCount:(Int)->Unit,next:()->Unit){Column(Modifier.padding(24.dp)){Header("Paso 7 de 8","¿Cuántas comidas haces al día?");Text("TITÁN organizará tu plan alrededor de tu rutina habitual.",color=TitanTextSecondary);Spacer(Modifier.height(18.dp));(2..6).forEach{n->Card(onClick={setCount(n)},modifier=Modifier.fillMaxWidth().padding(vertical=5.dp),shape=RoundedCornerShape(18.dp),colors=CardDefaults.cardColors(containerColor=if(count==n)TitanPrimary.copy(alpha=.13f) else TitanCard),border=if(count==n)androidx.compose.foundation.BorderStroke(1.dp,TitanPrimary) else null){Row(Modifier.fillMaxWidth().padding(18.dp),verticalAlignment=Alignment.CenterVertically){Text("$n comidas",Modifier.weight(1f),fontWeight=FontWeight.Bold);Text(if(count==n)"✓" else "○",color=if(count==n)TitanPrimary else TitanTextSecondary,fontSize=22.sp)}}};Spacer(Modifier.weight(1f));PrimaryButton("Continuar",next)}}
@Composable private fun Maintenance(e:EnergyEstimate,next:()->Unit){var details by remember{mutableStateOf(false)};Column(Modifier.padding(horizontal=22.dp)){Header("Paso 8 de 8","Tu mantenimiento");Text("Según tus datos, tu gasto energético diario estimado es:",color=TitanTextSecondary);Spacer(Modifier.height(16.dp));Card(colors=CardDefaults.cardColors(containerColor=TitanCard),shape=RoundedCornerShape(22.dp)){Column(Modifier.fillMaxWidth().padding(22.dp)){Text(e.maintenance.toString()+" kcal",fontSize=38.sp,fontWeight=FontWeight.Bold);Text("VER CÓMO SE CALCULÓ "+if(details)"⌃" else "›",color=TitanPrimary,fontWeight=FontWeight.Bold,modifier=Modifier.clickable{details=!details}.padding(vertical=8.dp));AnimatedVisibility(details){Column{Text("GASTO BASAL  "+e.bmr+" kcal",color=TitanTextSecondary);Text("ACTIVIDAD BASE  "+e.baseWithActivity+" kcal",color=TitanTextSecondary);Text("TRABAJO  "+e.dailyActivityKcal+" kcal",color=TitanTextSecondary);Text("ENTRENAMIENTO  "+e.trainingKcal+" kcal",color=TitanTextSecondary)}}}};Spacer(Modifier.weight(1f));PrimaryButton("Elegir estrategia",next)}}
@Composable private fun Strategies(m:Int,current:Strategy,set:(Strategy)->Unit,next:()->Unit){Column(Modifier.padding(24.dp)){Header("Configuración inicial","Elige tu estrategia");TitanEngine.plans(m).forEach{p->Card(onClick={set(p.strategy)},modifier=Modifier.fillMaxWidth().padding(vertical=6.dp),colors=CardDefaults.cardColors(containerColor=if(p.strategy==current)TitanCard else TitanSurface)){Column(Modifier.padding(18.dp)){Text(when(p.strategy){Strategy.LOW->"Bajo";Strategy.MODERATE->"Moderado";Strategy.RIGOROUS->"Riguroso"},fontWeight=FontWeight.Bold);Text(p.target.toString()+" kcal · margen hasta "+p.toleranceCeiling,color=TitanTextSecondary)}}};Spacer(Modifier.weight(1f));PrimaryButton("Entrar en TITÁN",next)}}
@Composable private fun RowScope.MacroBar(label:String,value:Int,target:Int){val goal=if(target>0)(value.toFloat()/target).coerceIn(0f,1f) else 0f;val progress by animateFloatAsState(goal,tween(750),label="macro");Column(Modifier.weight(1f)){Text(label,style=MaterialTheme.typography.labelLarge);Text("$value / $target g",color=TitanTextSecondary,fontSize=12.sp);LinearProgressIndicator(progress={progress},modifier=Modifier.fillMaxWidth().height(5.dp),color=TitanSecondary,trackColor=TitanDivider)}}
@Composable private fun CalorieRing(b:DailyBalance,plan:CaloriePlan){val goal=(b.consumed/plan.target.toFloat()).coerceIn(0f,1f);val progress by animateFloatAsState(goal,tween(900,easing=FastOutSlowInEasing),label="calorieRing");Box(Modifier.size(210.dp),contentAlignment=Alignment.Center){Canvas(Modifier.fillMaxSize()){val stroke=18.dp.toPx();drawArc(TitanDivider,-90f,360f,false,style=Stroke(stroke,cap=StrokeCap.Round));drawArc(TitanPrimary,-90f,360f*progress,false,style=Stroke(stroke,cap=StrokeCap.Round))};Column(horizontalAlignment=Alignment.CenterHorizontally){Text("Te quedan",color=TitanTextSecondary);Text(b.availableToTarget.toString(),fontSize=42.sp,fontWeight=FontWeight.Bold);Text("kcal",color=TitanTextSecondary)}}}
@Composable private fun BottomNav(today:()->Unit,plan:()->Unit,progress:()->Unit,more:()->Unit){NavigationBar(containerColor=TitanSurface.copy(alpha=.97f),tonalElevation=10.dp){NavigationBarItem(true,today,{Text("●",color=TitanPrimary)},label={Text("HOY",fontWeight=FontWeight.Bold)},colors=NavigationBarItemDefaults.colors(indicatorColor=TitanPrimary.copy(alpha=.14f),selectedTextColor=TitanPrimary));NavigationBarItem(false,plan,{Text("◆")},label={Text("PLAN")});NavigationBarItem(false,progress,{Text("▲")},label={Text("PROGRESO")});NavigationBarItem(false,more,{Text("•••")},label={Text("MÁS")})}}
@Composable private fun Today(plan:CaloriePlan,b:DailyBalance,macros:MacroBalance,meals:List<MealSlot>,add:()->Unit,skip:(String)->Unit,close:()->Unit,week:()->Unit,quick:()->Unit,social:()->Unit){
 val cal=java.util.Calendar.getInstance()
 val currentDow=cal.get(java.util.Calendar.DAY_OF_WEEK)
 val mondayOffset=if(currentDow==java.util.Calendar.SUNDAY)-6 else java.util.Calendar.MONDAY-currentDow
 val days=(0..6).map{i->
  (cal.clone() as java.util.Calendar).apply{add(java.util.Calendar.DAY_OF_MONTH,mondayOffset+i)}
 }
 Scaffold(containerColor=Color.Transparent,bottomBar={BottomNav({},add,week,{})}){pad->
  Column(Modifier.padding(pad).padding(horizontal=20.dp).verticalScroll(androidx.compose.foundation.rememberScrollState()),horizontalAlignment=Alignment.CenterHorizontally){
   Spacer(Modifier.height(52.dp))
   Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){
    TitanMark()
    Spacer(Modifier.weight(1f))
    Surface(shape=RoundedCornerShape(50),color=TitanCard,modifier=Modifier.size(46.dp)){Box(contentAlignment=Alignment.Center){Text("●",color=TitanText,fontSize=22.sp)}}
   }
   Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween,verticalAlignment=Alignment.Top){
    days.forEach{d->
     val active=d.get(java.util.Calendar.YEAR)==cal.get(java.util.Calendar.YEAR) && d.get(java.util.Calendar.DAY_OF_YEAR)==cal.get(java.util.Calendar.DAY_OF_YEAR)
     Column(horizontalAlignment=Alignment.CenterHorizontally,modifier=Modifier.width(42.dp)){
      Surface(shape=RoundedCornerShape(50),color=if(active)TitanPrimary else Color.Transparent,border=androidx.compose.foundation.BorderStroke(1.dp,if(active)TitanPrimary else TitanDivider),modifier=Modifier.size(40.dp)){
       Box(contentAlignment=Alignment.Center){Text(when(d.get(java.util.Calendar.DAY_OF_WEEK)){java.util.Calendar.MONDAY->"L";java.util.Calendar.TUESDAY->"M";java.util.Calendar.WEDNESDAY->"X";java.util.Calendar.THURSDAY->"J";java.util.Calendar.FRIDAY->"V";java.util.Calendar.SATURDAY->"S";else->"D"},color=if(active)TitanBackground else TitanText,fontWeight=FontWeight.Bold)}
      }
      Spacer(Modifier.height(4.dp));Text(d.get(java.util.Calendar.DAY_OF_MONTH).toString(),fontSize=11.sp,color=if(active)TitanPrimary else TitanTextSecondary)
     }
    }
   }
   Spacer(Modifier.height(12.dp))
   Text("Hoy",fontSize=38.sp,fontWeight=FontWeight.ExtraBold,textAlign=TextAlign.Center,modifier=Modifier.fillMaxWidth())
   Text("Disciplina hoy. Resultados mañana.",color=TitanTextSecondary,fontSize=15.sp,textAlign=TextAlign.Center,modifier=Modifier.fillMaxWidth())
   Spacer(Modifier.height(12.dp))
   Box(Modifier.fillMaxWidth(),contentAlignment=Alignment.Center){CalorieRing(b,plan)}
   Spacer(Modifier.height(10.dp))
   Column(Modifier.fillMaxWidth(),verticalArrangement=Arrangement.spacedBy(8.dp)){
    Row(Modifier.fillMaxWidth()){ MacroBar("PROTEÍNA",macros.proteinG,macros.target.proteinG) }
    Row(Modifier.fillMaxWidth()){ MacroBar("CARBOS",macros.carbsG,macros.target.carbsG) }
    Row(Modifier.fillMaxWidth()){ MacroBar("GRASAS",macros.fatG,macros.target.fatG) }
   }
   Spacer(Modifier.height(14.dp))
   Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){
    meals.take(4).forEachIndexed{i,m->
     Surface(shape=RoundedCornerShape(14.dp),color=TitanCard.copy(alpha=.92f),modifier=Modifier.weight(1f).clickable{add()}){
      Column(Modifier.padding(vertical=11.dp,horizontal=4.dp),horizontalAlignment=Alignment.CenterHorizontally){
       Text(when(i){0->"☀";1->"♨";2->"●";else->"☾"},fontSize=20.sp,color=TitanText)
       Spacer(Modifier.height(4.dp))
       Text(m.name,fontSize=10.sp,fontWeight=FontWeight.Bold,maxLines=1)
       Text(when(m.status){MealStatus.PENDING->"Pendiente";MealStatus.CONFIRMED->"Confirmada";MealStatus.SKIPPED->"Omitida"},fontSize=9.sp,color=when(m.status){MealStatus.CONFIRMED->TitanSuccess;MealStatus.SKIPPED->TitanWarning;else->TitanTextSecondary})
      }
     }
    }
   }
  }
 }
}
@Composable private fun MealList(meals:List<MealSlot>,open:(MealSlot)->Unit,skip:(String)->Unit,back:()->Unit){Column(Modifier.padding(horizontal=22.dp)){Header("PLAN DE HOY","Mis comidas");Text("TU DÍA, ORGANIZADO SIN CONVERTIRLO EN UNA CÁRCEL.",color=TitanTextSecondary,fontSize=12.sp,letterSpacing=.6.sp);Spacer(Modifier.height(12.dp));meals.forEachIndexed{i,m->Card(onClick={if(m.status==MealStatus.PENDING)open(m)},colors=CardDefaults.cardColors(containerColor=TitanCard.copy(alpha=.9f)),shape=RoundedCornerShape(22.dp),modifier=Modifier.fillMaxWidth().padding(vertical=6.dp)){Row(Modifier.padding(15.dp),verticalAlignment=Alignment.CenterVertically){FoodVisual(Modifier.size(64.dp));Spacer(Modifier.width(14.dp));Column(Modifier.weight(1f)){Text(m.name.uppercase(),fontWeight=FontWeight.ExtraBold);Text(m.plannedKcal.toString()+" KCAL OBJETIVO",color=TitanTextSecondary,fontSize=11.sp);Spacer(Modifier.height(5.dp));Text(when(m.status){MealStatus.PENDING->"PENDIENTE";MealStatus.CONFIRMED->"✓ CONFIRMADA · "+m.consumedKcal+" KCAL";MealStatus.SKIPPED->"OMITIDA"},color=when(m.status){MealStatus.CONFIRMED->TitanSuccess;MealStatus.SKIPPED->TitanWarning;else->TitanPrimary},fontSize=11.sp,fontWeight=FontWeight.Bold)};if(m.status==MealStatus.PENDING)TextButton({skip(m.id)}){Text("OMITIR",fontSize=10.sp)}}}};Spacer(Modifier.weight(1f));TextButton(back,Modifier.fillMaxWidth()){Text("VOLVER A HOY")}}}
@Composable private fun DishProposal(d:Dish,change:()->Unit,ingredient:(Int)->Unit,confirm:()->Unit,back:()->Unit){Column(Modifier.padding(horizontal=22.dp)){Header("PLATO PROPUESTO",d.name);Card(colors=CardDefaults.cardColors(containerColor=TitanCard.copy(alpha=.92f)),shape=RoundedCornerShape(24.dp)){Column(Modifier.padding(20.dp)){FoodVisual(Modifier.fillMaxWidth().height(170.dp));Spacer(Modifier.height(16.dp));Text(d.kcal.toString()+" kcal",fontSize=30.sp,fontWeight=FontWeight.Bold);Text("Proteínas "+d.proteinG+" g · Carbohidratos "+d.carbsG+" g · Grasas "+d.fatG+" g",color=TitanTextSecondary);Spacer(Modifier.height(14.dp));d.ingredients.forEachIndexed{i,x->Row(Modifier.fillMaxWidth().padding(vertical=5.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(x.name,fontWeight=FontWeight.SemiBold);Text(x.grams.toString()+" g · "+x.kcal+" kcal",color=TitanTextSecondary)};TextButton({ingredient(i)}){Text("CAMBIAR")}}}};Spacer(Modifier.height(18.dp));PrimaryButton("CONFIRMAR PLATO",confirm);OutlinedButton(change,Modifier.fillMaxWidth().padding(top=10.dp)){Text("CAMBIAR PLATO")};TextButton(back,Modifier.fillMaxWidth()){Text("Atrás")}}}}
@Composable private fun Alternatives(target:Int,current:Dish,choose:(Dish)->Unit,back:()->Unit){
 Column(Modifier.padding(horizontal=22.dp)){
  Header("CAMBIAR PLATO","4 alternativas compatibles")
  MealEngine.alternatives(target,exclude=setOf(current.id)).forEach{d->
   Card(onClick={choose(d)},colors=CardDefaults.cardColors(containerColor=TitanCard.copy(alpha=.92f)),modifier=Modifier.fillMaxWidth().padding(vertical=5.dp)){
    Column(Modifier.padding(16.dp)){
     Text(d.name,fontWeight=FontWeight.Bold)
     Text(d.kcal.toString()+" kcal · P "+d.proteinG+" · C "+d.carbsG+" · G "+d.fatG,color=TitanTextSecondary)
    }
   }
  }
  Text("VER MÁS",color=TitanPrimary,modifier=Modifier.padding(16.dp))
  Spacer(Modifier.weight(1f))
  TextButton(back,Modifier.fillMaxWidth()){Text("VOLVER")}
 }
}

@Composable private fun IngredientEditor(d:Dish,index:Int,resize:(Int)->Unit,replace:(Ingredient)->Unit,back:()->Unit){val item=d.ingredients[index];var grams by remember(item.id,item.grams){mutableStateOf(item.grams.toString())};Column(Modifier.padding(horizontal=22.dp)){Header("INGREDIENTE",item.name);Text("Cambiar cantidad",color=TitanTextSecondary);Field("Gramos",grams){grams=it;it.toIntOrNull()?.let(resize)};Spacer(Modifier.height(16.dp));Text("Sustituir por",fontWeight=FontWeight.Bold);MealEngine.ingredientAlternatives(d,index).forEach{x->Card(onClick={replace(x)},colors=CardDefaults.cardColors(containerColor=TitanCard.copy(alpha=.92f)),modifier=Modifier.fillMaxWidth().padding(vertical=5.dp)){Row(Modifier.padding(16.dp)){Text(x.name,Modifier.weight(1f));Text(x.kcal.toString()+" kcal",color=TitanTextSecondary)}}};Spacer(Modifier.weight(1f));Text("El cambio mantiene aproximadamente el aporte energético del ingrediente original.",color=TitanTextSecondary,fontSize=12.sp);TextButton(back,Modifier.fillMaxWidth()){Text("VOLVER AL PLATO")}}}

@Composable private fun DayClose(r:DayCloseResult,remainingDays:Int,back:()->Unit){val recal=TitanEngine.weeklyRecalibration(r.excessToRecalibrate,remainingDays);Column(Modifier.padding(horizontal=22.dp)){Header("CIERRE DIARIO","Así termina tu día");Card(colors=CardDefaults.cardColors(containerColor=TitanCard),shape=RoundedCornerShape(22.dp)){Column(Modifier.padding(20.dp)){Text(r.consumed.toString()+" kcal",fontSize=36.sp,fontWeight=FontWeight.Bold);Text("Objetivo "+r.target+" · margen TITÁN "+r.toleranceCeiling,color=TitanTextSecondary);Spacer(Modifier.height(14.dp));Text(r.completedMeals.toString()+" comidas confirmadas · "+r.skippedMeals+" omitidas",color=TitanTextSecondary);Spacer(Modifier.height(14.dp));if(r.excessToRecalibrate==0)Text("Día dentro del margen. No hay compensación.",color=TitanSuccess,fontWeight=FontWeight.Bold)else{Text("Exceso sobre el margen: "+r.excessToRecalibrate+" kcal",color=TitanWarning,fontWeight=FontWeight.Bold);Text("Recalibración orientativa: "+recal.adjustmentPerDay+" kcal/día durante "+remainingDays+" días.",color=TitanTextSecondary)}}};Spacer(Modifier.height(18.dp));Text("TITÁN compensa únicamente lo que supera tu margen, no una desviación normal del objetivo.",color=TitanTextSecondary);Spacer(Modifier.weight(1f));PrimaryButton("Continuar",back)}}

@Composable private fun WeekHistory(days:List<DayRecord>,review:()->Unit,body:()->Unit,back:()->Unit){Column(Modifier.padding(horizontal=22.dp)){Header("PROGRESO","Mi semana");if(days.isEmpty())Text("Aún no hay días registrados esta semana.",color=TitanTextSecondary)else{days.forEach{d->Card(colors=CardDefaults.cardColors(containerColor=TitanCard),modifier=Modifier.fillMaxWidth().padding(vertical=4.dp)){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(d.date,fontWeight=FontWeight.Bold);Text(d.consumed.toString()+" / "+d.target+" kcal",color=TitanTextSecondary)};Text(if(d.closed)"CERRADO" else "EN CURSO",color=if(d.closed)TitanSuccess else TitanWarning)}};val avg=days.map{it.consumed}.average().toInt();val excess=days.sumOf{it.excess};Spacer(Modifier.height(16.dp));Text("Media registrada: "+avg+" kcal/día",fontWeight=FontWeight.Bold);Text("Exceso acumulado sobre tolerancia: "+excess+" kcal",color=TitanTextSecondary)}};Spacer(Modifier.weight(1f));if(days.isNotEmpty())PrimaryButton("Revisión semanal",review);OutlinedButton(body,Modifier.fillMaxWidth().padding(top=8.dp)){Text("Progreso corporal")};TextButton(back,Modifier.fillMaxWidth()){Text("Volver a Hoy")}}}

@Composable private fun Score(label:String,value:Int,set:(Int)->Unit){Column(Modifier.padding(vertical=5.dp)){Text(label,fontWeight=FontWeight.SemiBold);Row{(1..5).forEach{n->FilterChip(value==n,{set(n)},{Text(n.toString())});Spacer(Modifier.width(5.dp))}}}}
@Composable private fun WeeklyReviewScreen(days:List<DayRecord>,currentTarget:Int,apply:(WeeklyAdjustment)->Unit,back:()->Unit){var hunger by remember{mutableStateOf(3)};var energy by remember{mutableStateOf(3)};var recovery by remember{mutableStateOf(3)};var performance by remember{mutableStateOf(3)};var stress by remember{mutableStateOf(3)};var satisfaction by remember{mutableStateOf(3)};var done by remember{mutableStateOf(false)};val review=TitanEngine.weeklyReview(days,WeeklyFeedback(hunger,energy,recovery,performance,stress,satisfaction));val adjustment=TitanEngine.weeklyAdjustment(review,currentTarget);Column(Modifier.padding(horizontal=22.dp)){Header("REVISIÓN SEMANAL","Cómo ha ido tu semana");if(!done){Score("Hambre",hunger){hunger=it};Score("Energía",energy){energy=it};Score("Recuperación",recovery){recovery=it};Score("Rendimiento",performance){performance=it};Score("Estrés",stress){stress=it};Score("Satisfacción",satisfaction){satisfaction=it};Spacer(Modifier.weight(1f));PrimaryButton("Analizar semana"){done=true}}else{Card(colors=CardDefaults.cardColors(containerColor=TitanCard),shape=RoundedCornerShape(22.dp)){Column(Modifier.padding(20.dp)){Text("Resumen",fontSize=24.sp,fontWeight=FontWeight.Bold);Text("Media diaria: "+review.averageKcal+" kcal",color=TitanTextSecondary);Text("Adherencia aproximada: "+review.adherencePercent+"%",color=TitanTextSecondary);Text("Exceso sobre tolerancia: "+review.excessOverTolerance+" kcal",color=TitanTextSecondary);Spacer(Modifier.height(16.dp));Text(if(adjustment.delta==0)"Objetivo sin cambios" else "Nuevo objetivo: "+adjustment.nextTarget+" kcal",fontWeight=FontWeight.Bold,color=TitanPrimary);Text(adjustment.reason,color=TitanTextSecondary)}};Spacer(Modifier.weight(1f));if(adjustment.delta!=0)PrimaryButton("Aplicar ajuste"){apply(adjustment)} else PrimaryButton("Mantener objetivo"){apply(adjustment)};TextButton(back,Modifier.fillMaxWidth()){Text("Volver sin aplicar")}}}}

@Composable private fun BodyProgress(entries:List<BodyEntry>,save:(Double,Double?)->Unit,back:()->Unit){var weight by remember{mutableStateOf("")};var waist by remember{mutableStateOf("")};var refresh by remember{mutableStateOf(0)};val trend=TitanEngine.bodyTrend(entries);Column(Modifier.padding(horizontal=22.dp)){Header("PROGRESO","Composición corporal");Text("Registra peso y cintura. TITÁN usará la tendencia, no un dato aislado.",color=TitanTextSecondary);Field("Peso (kg)",weight){weight=it};Field("Cintura (cm, opcional)",waist){waist=it};Button({weight.toDoubleOrNull()?.let{save(it,waist.toDoubleOrNull());refresh++}},Modifier.fillMaxWidth(),colors=ButtonDefaults.buttonColors(containerColor=TitanPrimary,contentColor=TitanBackground)){Text("Guardar registro",fontWeight=FontWeight.Bold)};Spacer(Modifier.height(18.dp));Card(colors=CardDefaults.cardColors(containerColor=TitanCard),shape=RoundedCornerShape(22.dp)){Column(Modifier.padding(18.dp)){Text("Tendencia",fontWeight=FontWeight.Bold,fontSize=22.sp);Text(trend.message,color=TitanTextSecondary);if(trend.entries>=2){Text("Cambio de peso: "+String.format("%.1f",trend.weightChangeKg)+" kg");Text("Ritmo aproximado: "+String.format("%.2f",trend.weeklyWeightRateKg)+" kg/semana",color=TitanTextSecondary);trend.waistChangeCm?.let{Text("Cambio de cintura: "+String.format("%.1f",it)+" cm",color=TitanTextSecondary)}}}};Spacer(Modifier.height(12.dp));entries.takeLast(5).reversed().forEach{e->Text(e.date+" · "+e.weightKg+" kg"+(e.waistCm?.let{" · cintura "+it+" cm"}?:""),color=TitanTextSecondary)};Spacer(Modifier.weight(1f));TextButton(back,Modifier.fillMaxWidth()){Text("Volver")}}}

@Composable private fun AddMeal(done:(String,Int)->Unit,back:()->Unit){var q by remember{mutableStateOf("")};var selected by remember{mutableStateOf<FoodItem?>(null)};var grams by remember{mutableStateOf("100")};Column(Modifier.padding(horizontal=22.dp)){Header("NUTRICIÓN","Añadir comida");Row(Modifier.fillMaxWidth()){Surface(shape=RoundedCornerShape(18.dp),color=TitanPrimary.copy(alpha=.16f)){Text("ALIMENTOS",Modifier.padding(horizontal=16.dp,vertical=9.dp),color=TitanPrimary,fontWeight=FontWeight.Bold)};Spacer(Modifier.width(8.dp));Surface(shape=RoundedCornerShape(18.dp),color=TitanSurface){Text("COMIDAS SOCIALES",Modifier.padding(horizontal=16.dp,vertical=9.dp),color=TitanTextSecondary,fontWeight=FontWeight.Bold,fontSize=11.sp)}};Spacer(Modifier.height(10.dp));TextFieldInput("Buscar alimento",q){q=it};selected?.let{food->Card(colors=CardDefaults.cardColors(containerColor=TitanCard),shape=RoundedCornerShape(24.dp),modifier=Modifier.fillMaxWidth().padding(top=8.dp)){Column(Modifier.padding(18.dp)){FoodVisual(Modifier.fillMaxWidth().height(150.dp));Spacer(Modifier.height(14.dp));Text(food.name.uppercase(),fontWeight=FontWeight.ExtraBold,fontSize=21.sp);Field("Cantidad (g)",grams){grams=it};val g=grams.toIntOrNull()?:100;Text(MealEngine.foodKcal(food,g).toString()+" KCAL",color=TitanPrimary,fontWeight=FontWeight.ExtraBold,fontSize=24.sp);Spacer(Modifier.height(10.dp));PrimaryButton("AÑADIR A MI DÍA"){done(food.name,MealEngine.foodKcal(food,g))};TextButton({selected=null},Modifier.fillMaxWidth()){Text("CAMBIAR ALIMENTO")}}}}?:run{Text("RESULTADOS",fontSize=11.sp,color=TitanTextSecondary,fontWeight=FontWeight.Bold);MealEngine.searchFoods(q).take(8).forEachIndexed{i,food->Card(onClick={selected=food},colors=CardDefaults.cardColors(containerColor=TitanCard.copy(alpha=.9f)),shape=RoundedCornerShape(18.dp),modifier=Modifier.fillMaxWidth().padding(vertical=4.dp)){Row(Modifier.padding(12.dp),verticalAlignment=Alignment.CenterVertically){FoodVisual(Modifier.size(48.dp));Spacer(Modifier.width(12.dp));Text(food.name,Modifier.weight(1f),fontWeight=FontWeight.SemiBold);Text(food.kcalPer100.toString()+" kcal",color=TitanTextSecondary,fontSize=12.sp)}}}};Spacer(Modifier.weight(1f));TextButton(back,Modifier.fillMaxWidth()){Text("VOLVER")}}}
@Composable private fun SocialMealScreen(done:(String,Int)->Unit,back:()->Unit){var selected by remember{mutableStateOf<SocialMeal?>(null)};var amount by remember{mutableStateOf(SocialAmount.NORMAL)};Column(Modifier.padding(horizontal=22.dp)){Header("COMIDAS SOCIALES","Estimación rápida");Text("No necesitas pesar. Elige una referencia y cuánto comiste.",color=TitanTextSecondary);selected?.let{meal->Text(meal.name,fontWeight=FontWeight.Bold,fontSize=24.sp);Row{SocialAmount.entries.forEach{a->FilterChip(amount==a,{amount=a},{Text(when(a){SocialAmount.LITTLE->"POCO";SocialAmount.NORMAL->"NORMAL";SocialAmount.A_LOT->"BASTANTE"})});Spacer(Modifier.width(6.dp))}};Text("Estimación: "+MealEngine.socialKcal(meal,amount)+" kcal",color=TitanPrimary,fontWeight=FontWeight.Bold);PrimaryButton("Añadir comida social"){done(meal.name,MealEngine.socialKcal(meal,amount))}}?:run{MealEngine.socialMeals.forEach{meal->Card(onClick={selected=meal},colors=CardDefaults.cardColors(containerColor=TitanCard),modifier=Modifier.fillMaxWidth().padding(vertical=5.dp)){Text(meal.name,Modifier.padding(18.dp),fontWeight=FontWeight.SemiBold)}}};Spacer(Modifier.weight(1f));TextButton(back,Modifier.fillMaxWidth()){Text("Volver")}}}