package com.blsd.titan

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*\nimport androidx.compose.foundation.Canvas\nimport androidx.compose.foundation.background
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp\nimport androidx.compose.ui.graphics.StrokeCap\nimport androidx.compose.ui.graphics.drawscope.Stroke\nimport androidx.compose.ui.geometry.Offset\nimport androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.platform.LocalContext

class MainActivity:ComponentActivity(){
 override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);setContent{TitanTheme{TitanApp()}}}
}
private enum class Screen{WELCOME,PROFILE,WORK,WORK_DETAIL,TRAINING,MAINTENANCE,STRATEGY,TODAY,MEALS,DISH,ALTERNATIVES,INGREDIENT,DAY_CLOSE,WEEK,WEEK_REVIEW,BODY,ADD,SOCIAL}

@Composable fun TitanApp(){
 val context=LocalContext.current
 val store=remember{TitanStore(context)}
 val saved=remember{store.load()}
 var screen by remember{mutableStateOf(if(saved!=null)Screen.TODAY else Screen.WELCOME)}
 var sex by remember{mutableStateOf(saved?.sex?:Sex.MALE)}
 var age by remember{mutableStateOf((saved?.age?:39).toString())};var height by remember{mutableStateOf((saved?.heightCm?:170.0).toInt().toString())};var weight by remember{mutableStateOf((saved?.weightKg?:93.0).toInt().toString())}
 var standing by remember{mutableStateOf("7")};var moving by remember{mutableStateOf("5")};var load by remember{mutableStateOf("2")};var breaks by remember{mutableStateOf("1")};var workIntensity by remember{mutableStateOf(WorkIntensity.MODERATE)};var variableDay by remember{mutableStateOf(true)}
 var sessions by remember{mutableStateOf("4")};var minutes by remember{mutableStateOf("75")};var trainingIntensity by remember{mutableStateOf(TrainingIntensity.HIGH)}
 var estimate by remember{mutableStateOf<EnergyEstimate?>(saved?.let{EnergyEstimate(0,0,0,0,it.maintenance)})};var strategy by remember{mutableStateOf(saved?.strategy?:Strategy.MODERATE)}
 var selectedMealId by remember{mutableStateOf<String?>(null)};var proposedDish by remember{mutableStateOf<Dish?>(null)};var selectedIngredient by remember{mutableStateOf(0)}
 var meals by remember{mutableStateOf(saved?.let{val base=TitanEngine.plans(it.maintenance).first{p->p.strategy==it.strategy};store.ensureToday(base.copy(target=store.activeTarget(base.target))).meals}?:emptyList())}
 fun currentPlan():CaloriePlan{val m=estimate?.maintenance?:1;val base=TitanEngine.plans(m).first{it.strategy==strategy};val target=store.activeTarget(base.target);return base.copy(target=target)}
 Surface(Modifier.fillMaxSize(),color=TitanBackground){
  when(screen){
   Screen.WELCOME->Welcome{screen=Screen.PROFILE}
   Screen.PROFILE->Profile(age,{age=it},height,{height=it},weight,{weight=it},sex,{sex=it}){screen=Screen.WORK}
   Screen.WORK->Work(standing,{standing=it},moving,{moving=it},load,{load=it}){screen=Screen.WORK_DETAIL}
   Screen.WORK_DETAIL->WorkDetail(breaks,{breaks=it},workIntensity,{workIntensity=it},variableDay,{variableDay=it}){screen=Screen.TRAINING}
   Screen.TRAINING->Training(sessions,{sessions=it},minutes,{minutes=it},trainingIntensity,{trainingIntensity=it}){
    val w=weight.toDoubleOrNull()?:70.0
    val qe=QuestionnaireEngine.energy(w,ActivityQuestionnaire(standing.toDoubleOrNull()?:0.0,moving.toDoubleOrNull()?:0.0,load.toDoubleOrNull()?:0.0,workIntensity,breaks.toDoubleOrNull()?:0.0,variableDay),TrainingQuestionnaire(sessions.toIntOrNull()?:0,minutes.toIntOrNull()?:0,trainingIntensity))
    estimate=TitanEngine.estimateEnergy(UserProfile(sex,age.toIntOrNull()?:30,height.toDoubleOrNull()?:170.0,w,1.2,qe.workDailyKcal,qe.trainingDailyKcal));screen=Screen.MAINTENANCE
   }
   Screen.MAINTENANCE->Maintenance(estimate!!){screen=Screen.STRATEGY}
   Screen.STRATEGY->Strategies(estimate!!.maintenance,strategy,{strategy=it}){
    val profile=UserProfile(sex,age.toIntOrNull()?:30,height.toDoubleOrNull()?:170.0,weight.toDoubleOrNull()?:70.0)
    store.save(profile,estimate!!.maintenance,strategy)
    meals=TitanEngine.distribute(currentPlan().target,listOf("Desayuno","Comida","Merienda","Cena"));store.saveDay(meals,currentPlan());screen=Screen.TODAY}
   Screen.TODAY->{val p=currentPlan();Today(p,TitanEngine.balance(p,meals.sumOf{it.consumedKcal}),MealEngine.macroBalance(MealEngine.macroTarget(weight,p.target),meals),meals,{screen=Screen.ADD},{id->meals=meals.map{if(it.id==id)it.copy(status=MealStatus.SKIPPED)else it}.let(TitanEngine::redistribute)})}
   Screen.MEALS->MealList(meals,{m->selectedMealId=m.id;proposedDish=MealEngine.propose(m.plannedKcal);screen=Screen.DISH},{id->meals=meals.map{if(it.id==id)it.copy(status=MealStatus.SKIPPED)else it}.let(TitanEngine::redistribute)},{screen=Screen.TODAY})
   Screen.DISH->DishProposal(proposedDish!!,{screen=Screen.ALTERNATIVES},{index->selectedIngredient=index;screen=Screen.INGREDIENT},{
    val id=selectedMealId;val d=proposedDish!!;meals=meals.map{if(it.id==id)it.copy(name=d.name,consumedKcal=d.kcal,status=MealStatus.CONFIRMED,proteinG=d.proteinG,carbsG=d.carbsG,fatG=d.fatG)else it}.let(TitanEngine::redistribute);store.saveDay(meals,currentPlan());screen=Screen.MEALS
   },{screen=Screen.MEALS})
   Screen.ALTERNATIVES->Alternatives(meals.first{it.id==selectedMealId}.plannedKcal,proposedDish!!,{d->proposedDish=d;screen=Screen.DISH},{screen=Screen.DISH})
   Screen.INGREDIENT->IngredientEditor(proposedDish!!,selectedIngredient,{g->proposedDish=MealEngine.resizeIngredient(proposedDish!!,selectedIngredient,g)},{replacement->proposedDish=MealEngine.replaceIngredient(proposedDish!!,selectedIngredient,replacement);screen=Screen.DISH},{screen=Screen.DISH})
   Screen.DAY_CLOSE->DayClose(TitanEngine.closeDay(currentPlan(),meals),store.remainingDaysInWeek()){store.saveDay(meals,currentPlan(),closed=true);screen=Screen.WEEK}
   Screen.WEEK->WeekHistory(store.weekHistory(),{screen=Screen.WEEK_REVIEW},{screen=Screen.BODY}){screen=Screen.TODAY}
   Screen.BODY->BodyProgress(store.bodyHistory(),{w,waist->store.saveBodyEntry(w,waist)},{screen=Screen.TODAY})
   Screen.WEEK_REVIEW->WeeklyReviewScreen(store.weekHistory(),currentPlan().target,{adjustment->store.applyWeeklyAdjustment(adjustment);val names=listOf("Desayuno","Comida","Merienda","Cena");meals=TitanEngine.distribute(adjustment.nextTarget,names);store.saveDay(meals,currentPlan());screen=Screen.TODAY},{screen=Screen.TODAY})
   Screen.SOCIAL->SocialMealScreen({name,kcal->meals=meals+MealSlot("social-"+System.currentTimeMillis(),name,kcal,kcal,MealStatus.CONFIRMED);store.saveDay(meals,currentPlan());screen=Screen.TODAY},{screen=Screen.TODAY})
   Screen.ADD->AddMeal({n,k->val i=meals.indexOfFirst{it.status==MealStatus.PENDING};if(i>=0)meals=meals.mapIndexed{x,m->if(x==i)m.copy(name=n,consumedKcal=k,status=MealStatus.CONFIRMED)else m}.let(TitanEngine::redistribute);screen=Screen.TODAY}){screen=Screen.TODAY}
  }
 }
}
@Composable private fun TitanMark(){Canvas(Modifier.size(116.dp)){val w=size.width;val h=size.height;val sw=w*.12f;drawLine(TitanText,Offset(w*.16f,h*.22f),Offset(w*.46f,h*.22f),sw,StrokeCap.Square);drawLine(TitanText,Offset(w*.31f,h*.22f),Offset(w*.31f,h*.78f),sw,StrokeCap.Square);drawLine(TitanText,Offset(w*.54f,h*.22f),Offset(w*.84f,h*.22f),sw,StrokeCap.Square);drawLine(TitanText,Offset(w*.69f,h*.22f),Offset(w*.69f,h*.78f),sw,StrokeCap.Square)}}
@Composable private fun Welcome(next:()->Unit){Column(Modifier.fillMaxSize().background(TitanBackground).padding(28.dp),verticalArrangement=Arrangement.SpaceBetween,horizontalAlignment=Alignment.CenterHorizontally){Column(Modifier.padding(top=62.dp),horizontalAlignment=Alignment.CenterHorizontally){TitanMark();Text("T I T Á N",style=MaterialTheme.typography.headlineLarge);Text("DATOS QUE TE LLEVAN MÁS LEJOS",style=MaterialTheme.typography.labelLarge,color=TitanTextSecondary);Spacer(Modifier.height(46.dp));Text("MÁS QUE UNA APP. UN MÉTODO.",style=MaterialTheme.typography.headlineMedium,textAlign=TextAlign.Center);Spacer(Modifier.height(16.dp));Text("Nutrición inteligente  ·  Rendimiento real\nHábitos sostenibles  ·  Tu mejor versión",color=TitanTextSecondary,textAlign=TextAlign.Center,lineHeight=24.sp)};Column(Modifier.fillMaxWidth()){Text("DISCIPLINA HOY. RESULTADOS MAÑANA.",style=MaterialTheme.typography.labelLarge,color=TitanTextSecondary,modifier=Modifier.fillMaxWidth(),textAlign=TextAlign.Center);Spacer(Modifier.height(14.dp));PrimaryButton("Comenzar",next)}}}
@Composable private fun Header(step:String,title:String){Spacer(Modifier.height(26.dp));Text(step.uppercase(),color=TitanPrimary,style=MaterialTheme.typography.labelLarge);Spacer(Modifier.height(8.dp));Text(title,style=MaterialTheme.typography.headlineLarge);Spacer(Modifier.height(20.dp))}
@Composable private fun Field(label:String,value:String,set:(String)->Unit){OutlinedTextField(value,{set(it.filter(Char::isDigit))},label={Text(label)},modifier=Modifier.fillMaxWidth().padding(vertical=5.dp),colors=OutlinedTextFieldDefaults.colors(focusedBorderColor=TitanPrimary,unfocusedBorderColor=TitanDivider))}
@Composable private fun PrimaryButton(label:String,go:()->Unit){Button(go,Modifier.fillMaxWidth().height(56.dp),shape=RoundedCornerShape(18.dp),colors=ButtonDefaults.buttonColors(containerColor=TitanPrimary,contentColor=TitanBackground)){Text(label,fontWeight=FontWeight.Bold)}}
@Composable private fun Profile(age:String,setAge:(String)->Unit,height:String,setHeight:(String)->Unit,weight:String,setWeight:(String)->Unit,sex:Sex,setSex:(Sex)->Unit,next:()->Unit){Column(Modifier.padding(24.dp)){Header("Paso 1 de 5","Tus datos");Row{FilterChip(sex==Sex.MALE,{setSex(Sex.MALE)},{Text("Hombre")});Spacer(Modifier.width(8.dp));FilterChip(sex==Sex.FEMALE,{setSex(Sex.FEMALE)},{Text("Mujer")})};Field("Edad",age,setAge);Field("Altura (cm)",height,setHeight);Field("Peso (kg)",weight,setWeight);Spacer(Modifier.weight(1f));PrimaryButton("Continuar",next)}}
@Composable private fun Work(a:String,sa:(String)->Unit,b:String,sb:(String)->Unit,c:String,sc:(String)->Unit,next:()->Unit){Column(Modifier.padding(24.dp)){Header("Paso 2 de 5","Tu actividad diaria");Text("Queremos medir tu día real, no asignarte una etiqueta genérica.",color=TitanTextSecondary);Field("Horas de pie",a,sa);Field("Horas en movimiento",b,sb);Field("Horas con cargas / trabajo físico",c,sc);Spacer(Modifier.weight(1f));PrimaryButton("Continuar",next)}}
@Composable private fun WorkDetail(breaks:String,setBreaks:(String)->Unit,intensity:WorkIntensity,setIntensity:(WorkIntensity)->Unit,variable:Boolean,setVariable:(Boolean)->Unit,next:()->Unit){Column(Modifier.padding(24.dp)){Header("Paso 3 de 5","Cómo es tu jornada");Field("Horas totales de pausas",breaks,setBreaks);Text("Intensidad habitual",color=TitanTextSecondary);Row{WorkIntensity.entries.forEach{v->FilterChip(intensity==v,{setIntensity(v)},{Text(when(v){WorkIntensity.LOW->"Baja";WorkIntensity.MODERATE->"Media";WorkIntensity.HIGH->"Alta"})});Spacer(Modifier.width(6.dp))}};Spacer(Modifier.height(12.dp));Text("¿Tu actividad cambia mucho de un día a otro?",color=TitanTextSecondary);Row{FilterChip(variable,{setVariable(true)},{Text("Sí")});Spacer(Modifier.width(8.dp));FilterChip(!variable,{setVariable(false)},{Text("No")})};Spacer(Modifier.weight(1f));PrimaryButton("Continuar",next)}}
@Composable private fun Training(a:String,sa:(String)->Unit,b:String,sb:(String)->Unit,intensity:TrainingIntensity,setIntensity:(TrainingIntensity)->Unit,next:()->Unit){Column(Modifier.padding(24.dp)){Header("Paso 4 de 5","Tu entrenamiento");Text("Frecuencia, duración e intensidad alimentan la estimación inicial.",color=TitanTextSecondary);Field("Sesiones por semana",a,sa);Field("Minutos por sesión",b,sb);Text("Intensidad habitual",color=TitanTextSecondary);Row{TrainingIntensity.entries.forEach{v->FilterChip(intensity==v,{setIntensity(v)},{Text(when(v){TrainingIntensity.LIGHT->"Suave";TrainingIntensity.MODERATE->"Media";TrainingIntensity.HIGH->"Alta"})});Spacer(Modifier.width(6.dp))}};Spacer(Modifier.weight(1f));PrimaryButton("Calcular mantenimiento",next)}}
@Composable private fun Maintenance(e:EnergyEstimate,next:()->Unit){Column(Modifier.padding(24.dp)){Header("Paso 5 de 5","Tu mantenimiento");Text("Según tus datos, tu gasto energético diario estimado es:",color=TitanTextSecondary);Spacer(Modifier.height(16.dp));Card(colors=CardDefaults.cardColors(containerColor=TitanCard),shape=RoundedCornerShape(22.dp)){Column(Modifier.fillMaxWidth().padding(22.dp)){Text(e.maintenance.toString()+" kcal",fontSize=38.sp,fontWeight=FontWeight.Bold);Text("VER CÓMO SE CALCULÓ ›",color=TitanPrimary);Spacer(Modifier.height(14.dp));Text("Basal "+e.bmr+" · actividad base "+e.baseWithActivity+" · trabajo "+e.dailyActivityKcal+" · entrenamiento "+e.trainingKcal,color=TitanTextSecondary)}};Spacer(Modifier.weight(1f));PrimaryButton("Elegir estrategia",next)}}
@Composable private fun Strategies(m:Int,current:Strategy,set:(Strategy)->Unit,next:()->Unit){Column(Modifier.padding(24.dp)){Header("Configuración inicial","Elige tu estrategia");TitanEngine.plans(m).forEach{p->Card(onClick={set(p.strategy)},modifier=Modifier.fillMaxWidth().padding(vertical=6.dp),colors=CardDefaults.cardColors(containerColor=if(p.strategy==current)TitanCard else TitanSurface)){Column(Modifier.padding(18.dp)){Text(when(p.strategy){Strategy.LOW->"Bajo";Strategy.MODERATE->"Moderado";Strategy.RIGOROUS->"Riguroso"},fontWeight=FontWeight.Bold);Text(p.target.toString()+" kcal · margen hasta "+p.toleranceCeiling,color=TitanTextSecondary)}}};Spacer(Modifier.weight(1f));PrimaryButton("Entrar en TITÁN",next)}}
@Composable private fun MacroBar(label:String,value:Int,target:Int){Column(Modifier.weight(1f)){Text(label,style=MaterialTheme.typography.labelLarge);Text("$value / $target g",color=TitanTextSecondary,fontSize=12.sp);LinearProgressIndicator(progress={if(target>0)(value.toFloat()/target).coerceIn(0f,1f) else 0f},modifier=Modifier.fillMaxWidth().height(5.dp),color=TitanSecondary,trackColor=TitanDivider)}}
@Composable private fun CalorieRing(b:DailyBalance,plan:CaloriePlan){Box(Modifier.size(210.dp),contentAlignment=Alignment.Center){Canvas(Modifier.fillMaxSize()){val stroke=18.dp.toPx();drawArc(TitanDivider,-90f,360f,false,style=Stroke(stroke,cap=StrokeCap.Round));drawArc(TitanPrimary,-90f,360f*(b.consumed/plan.target.toFloat()).coerceIn(0f,1f),false,style=Stroke(stroke,cap=StrokeCap.Round))};Column(horizontalAlignment=Alignment.CenterHorizontally){Text("Te quedan",color=TitanTextSecondary);Text(b.availableToTarget.toString(),fontSize=42.sp,fontWeight=FontWeight.Bold);Text("kcal",color=TitanTextSecondary)}}}
@Composable private fun BottomNav(today:()->Unit,plan:()->Unit,progress:()->Unit,more:()->Unit){NavigationBar(containerColor=TitanSurface){NavigationBarItem(true,today,{Text("HOY")},label={Text("Hoy")});NavigationBarItem(false,plan,{Text("PLAN")},label={Text("Plan")});NavigationBarItem(false,progress,{Text("PROG.")},label={Text("Progreso")});NavigationBarItem(false,more,{Text("MÁS")},label={Text("Más")})}}
@Composable private fun Today(plan:CaloriePlan,b:DailyBalance,macros:MacroBalance,meals:List<MealSlot>,add:()->Unit,skip:(String)->Unit,close:()->Unit,week:()->Unit,quick:()->Unit,social:()->Unit){Scaffold(containerColor=TitanBackground,bottomBar={BottomNav({},add,week,{})}){pad->Column(Modifier.padding(pad).padding(horizontal=22.dp)){Spacer(Modifier.height(24.dp));Text("Hoy",style=MaterialTheme.typography.headlineLarge);Text(java.time.LocalDate.now().toString(),color=TitanTextSecondary);Spacer(Modifier.height(20.dp));Box(Modifier.fillMaxWidth(),contentAlignment=Alignment.Center){CalorieRing(b,plan)};Spacer(Modifier.height(18.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(12.dp)){MacroBar("Proteínas",macros.proteinG,macros.target.proteinG);MacroBar("Carbohidratos",macros.carbsG,macros.target.carbsG);MacroBar("Grasas",macros.fatG,macros.target.fatG)};Spacer(Modifier.height(20.dp));PrimaryButton("Ver mis comidas",add);Spacer(Modifier.height(12.dp));Row(Modifier.fillMaxWidth()){OutlinedButton(quick,Modifier.weight(1f)){Text("Añadir alimento")};Spacer(Modifier.width(8.dp));OutlinedButton(social,Modifier.weight(1f)){Text("Comida social")}};Spacer(Modifier.height(8.dp));TextButton(close,Modifier.fillMaxWidth()){Text("Cerrar día")}}}}
@Composable private fun MealList(meals:List<MealSlot>,open:(MealSlot)->Unit,skip:(String)->Unit,back:()->Unit){Column(Modifier.padding(22.dp)){Header("HOY","Mis comidas");meals.forEach{m->Card(onClick={if(m.status==MealStatus.PENDING)open(m)},colors=CardDefaults.cardColors(containerColor=TitanCard),modifier=Modifier.fillMaxWidth().padding(vertical=5.dp)){Row(Modifier.padding(16.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(m.name,fontWeight=FontWeight.Bold);Text(when(m.status){MealStatus.PENDING->"Pendiente · objetivo "+m.plannedKcal+" kcal";MealStatus.CONFIRMED->"COMIDA HECHA · "+m.consumedKcal+" kcal";MealStatus.SKIPPED->"OMITIDA"},color=if(m.status==MealStatus.CONFIRMED)TitanSuccess else TitanTextSecondary)};if(m.status==MealStatus.PENDING)TextButton({skip(m.id)}){Text("Omitir")}}}};Spacer(Modifier.weight(1f));TextButton(back,Modifier.fillMaxWidth()){Text("Volver a Hoy")}}}
@Composable private fun DishProposal(d:Dish,change:()->Unit,ingredient:(Int)->Unit,confirm:()->Unit,back:()->Unit){Column(Modifier.padding(24.dp)){Header("PLATO PROPUESTO",d.name);Card(colors=CardDefaults.cardColors(containerColor=TitanCard),shape=RoundedCornerShape(22.dp)){Column(Modifier.padding(20.dp)){Text(d.kcal.toString()+" kcal",fontSize=30.sp,fontWeight=FontWeight.Bold);Text("Proteínas "+d.proteinG+" g · Carbohidratos "+d.carbsG+" g · Grasas "+d.fatG+" g",color=TitanTextSecondary);Spacer(Modifier.height(14.dp));d.ingredients.forEachIndexed{i,x->Row(Modifier.fillMaxWidth().padding(vertical=5.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(x.name,fontWeight=FontWeight.SemiBold);Text(x.grams.toString()+" g · "+x.kcal+" kcal",color=TitanTextSecondary)};TextButton({ingredient(i)}){Text("Cambiar")}}}};Spacer(Modifier.height(18.dp));PrimaryButton("Confirmar plato",confirm);OutlinedButton(change,Modifier.fillMaxWidth().padding(top=10.dp)){Text("Cambiar plato")};TextButton(back,Modifier.fillMaxWidth()){Text("Atrás")}}}
@Composable private fun Alternatives(target:Int,current:Dish,choose:(Dish)->Unit,back:()->Unit){Column(Modifier.padding(24.dp)){Header("CAMBIAR PLATO","4 alternativas compatibles");MealEngine.alternatives(target,exclude=setOf(current.id)).forEach{d->Card(onClick={choose(d)},colors=CardDefaults.cardColors(containerColor=TitanCard),modifier=Modifier.fillMaxWidth().padding(vertical=5.dp)){Column(Modifier.padding(16.dp)){Text(d.name,fontWeight=FontWeight.Bold);Text(d.kcal.toString()+" kcal · P "+d.proteinG+" · C "+d.carbsG+" · G "+d.fatG,color=TitanTextSecondary)}}};Text("VER MÁS",color=TitanPrimary,modifier=Modifier.padding(16.dp));Spacer(Modifier.weight(1f));TextButton(back,Modifier.fillMaxWidth()){Text("Volver")}}}

@Composable private fun IngredientEditor(d:Dish,index:Int,resize:(Int)->Unit,replace:(Ingredient)->Unit,back:()->Unit){val item=d.ingredients[index];var grams by remember(item.id,item.grams){mutableStateOf(item.grams.toString())};Column(Modifier.padding(24.dp)){Header("INGREDIENTE",item.name);Text("Cambiar cantidad",color=TitanTextSecondary);Field("Gramos",grams){grams=it;it.toIntOrNull()?.let(resize)};Spacer(Modifier.height(16.dp));Text("Sustituir por",fontWeight=FontWeight.Bold);MealEngine.ingredientAlternatives(d,index).forEach{x->Card(onClick={replace(x)},colors=CardDefaults.cardColors(containerColor=TitanCard),modifier=Modifier.fillMaxWidth().padding(vertical=5.dp)){Row(Modifier.padding(16.dp)){Text(x.name,Modifier.weight(1f));Text(x.kcal.toString()+" kcal",color=TitanTextSecondary)}}};Spacer(Modifier.weight(1f));Text("El cambio mantiene aproximadamente el aporte energético del ingrediente original.",color=TitanTextSecondary,fontSize=12.sp);TextButton(back,Modifier.fillMaxWidth()){Text("Volver al plato")}}}

@Composable private fun DayClose(r:DayCloseResult,remainingDays:Int,back:()->Unit){val recal=TitanEngine.weeklyRecalibration(r.excessToRecalibrate,remainingDays);Column(Modifier.padding(24.dp)){Header("CIERRE DIARIO","Así termina tu día");Card(colors=CardDefaults.cardColors(containerColor=TitanCard),shape=RoundedCornerShape(22.dp)){Column(Modifier.padding(20.dp)){Text(r.consumed.toString()+" kcal",fontSize=36.sp,fontWeight=FontWeight.Bold);Text("Objetivo "+r.target+" · margen TITÁN "+r.toleranceCeiling,color=TitanTextSecondary);Spacer(Modifier.height(14.dp));Text(r.completedMeals.toString()+" comidas confirmadas · "+r.skippedMeals+" omitidas",color=TitanTextSecondary);Spacer(Modifier.height(14.dp));if(r.excessToRecalibrate==0)Text("Día dentro del margen. No hay compensación.",color=TitanSuccess,fontWeight=FontWeight.Bold)else{Text("Exceso sobre el margen: "+r.excessToRecalibrate+" kcal",color=TitanWarning,fontWeight=FontWeight.Bold);Text("Recalibración orientativa: "+recal.adjustmentPerDay+" kcal/día durante "+remainingDays+" días.",color=TitanTextSecondary)}}};Spacer(Modifier.height(18.dp));Text("TITÁN compensa únicamente lo que supera tu margen, no una desviación normal del objetivo.",color=TitanTextSecondary);Spacer(Modifier.weight(1f));PrimaryButton("Continuar",back)}}

@Composable private fun WeekHistory(days:List<DayRecord>,review:()->Unit,body:()->Unit,back:()->Unit){Column(Modifier.padding(24.dp)){Header("PROGRESO","Mi semana");if(days.isEmpty())Text("Aún no hay días registrados esta semana.",color=TitanTextSecondary)else{days.forEach{d->Card(colors=CardDefaults.cardColors(containerColor=TitanCard),modifier=Modifier.fillMaxWidth().padding(vertical=4.dp)){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(d.date,fontWeight=FontWeight.Bold);Text(d.consumed.toString()+" / "+d.target+" kcal",color=TitanTextSecondary)};Text(if(d.closed)"CERRADO" else "EN CURSO",color=if(d.closed)TitanSuccess else TitanWarning)}};val avg=days.map{it.consumed}.average().toInt();val excess=days.sumOf{it.excess};Spacer(Modifier.height(16.dp));Text("Media registrada: "+avg+" kcal/día",fontWeight=FontWeight.Bold);Text("Exceso acumulado sobre tolerancia: "+excess+" kcal",color=TitanTextSecondary)}};Spacer(Modifier.weight(1f));if(days.isNotEmpty())PrimaryButton("Revisión semanal",review);OutlinedButton(body,Modifier.fillMaxWidth().padding(top=8.dp)){Text("Progreso corporal")};TextButton(back,Modifier.fillMaxWidth()){Text("Volver a Hoy")}}}

@Composable private fun Score(label:String,value:Int,set:(Int)->Unit){Column(Modifier.padding(vertical=5.dp)){Text(label,fontWeight=FontWeight.SemiBold);Row{(1..5).forEach{n->FilterChip(value==n,{set(n)},{Text(n.toString())});Spacer(Modifier.width(5.dp))}}}}
@Composable private fun WeeklyReviewScreen(days:List<DayRecord>,currentTarget:Int,apply:(WeeklyAdjustment)->Unit,back:()->Unit){var hunger by remember{mutableStateOf(3)};var energy by remember{mutableStateOf(3)};var recovery by remember{mutableStateOf(3)};var performance by remember{mutableStateOf(3)};var stress by remember{mutableStateOf(3)};var satisfaction by remember{mutableStateOf(3)};var done by remember{mutableStateOf(false)};val review=TitanEngine.weeklyReview(days,WeeklyFeedback(hunger,energy,recovery,performance,stress,satisfaction));val adjustment=TitanEngine.weeklyAdjustment(review,currentTarget);Column(Modifier.padding(24.dp)){Header("REVISIÓN SEMANAL","Cómo ha ido tu semana");if(!done){Score("Hambre",hunger){hunger=it};Score("Energía",energy){energy=it};Score("Recuperación",recovery){recovery=it};Score("Rendimiento",performance){performance=it};Score("Estrés",stress){stress=it};Score("Satisfacción",satisfaction){satisfaction=it};Spacer(Modifier.weight(1f));PrimaryButton("Analizar semana"){done=true}}else{Card(colors=CardDefaults.cardColors(containerColor=TitanCard),shape=RoundedCornerShape(22.dp)){Column(Modifier.padding(20.dp)){Text("Resumen",fontSize=24.sp,fontWeight=FontWeight.Bold);Text("Media diaria: "+review.averageKcal+" kcal",color=TitanTextSecondary);Text("Adherencia aproximada: "+review.adherencePercent+"%",color=TitanTextSecondary);Text("Exceso sobre tolerancia: "+review.excessOverTolerance+" kcal",color=TitanTextSecondary);Spacer(Modifier.height(16.dp));Text(if(adjustment.delta==0)"Objetivo sin cambios" else "Nuevo objetivo: "+adjustment.nextTarget+" kcal",fontWeight=FontWeight.Bold,color=TitanPrimary);Text(adjustment.reason,color=TitanTextSecondary)}};Spacer(Modifier.weight(1f));if(adjustment.delta!=0)PrimaryButton("Aplicar ajuste"){apply(adjustment)} else PrimaryButton("Mantener objetivo"){apply(adjustment)};TextButton(back,Modifier.fillMaxWidth()){Text("Volver sin aplicar")}}}}

@Composable private fun BodyProgress(entries:List<BodyEntry>,save:(Double,Double?)->Unit,back:()->Unit){var weight by remember{mutableStateOf("")};var waist by remember{mutableStateOf("")};var refresh by remember{mutableStateOf(0)};val trend=TitanEngine.bodyTrend(entries);Column(Modifier.padding(24.dp)){Header("PROGRESO","Composición corporal");Text("Registra peso y cintura. TITÁN usará la tendencia, no un dato aislado.",color=TitanTextSecondary);Field("Peso (kg)",weight){weight=it};Field("Cintura (cm, opcional)",waist){waist=it};Button({weight.toDoubleOrNull()?.let{save(it,waist.toDoubleOrNull());refresh++}},Modifier.fillMaxWidth(),colors=ButtonDefaults.buttonColors(containerColor=TitanPrimary,contentColor=TitanBackground)){Text("Guardar registro",fontWeight=FontWeight.Bold)};Spacer(Modifier.height(18.dp));Card(colors=CardDefaults.cardColors(containerColor=TitanCard),shape=RoundedCornerShape(22.dp)){Column(Modifier.padding(18.dp)){Text("Tendencia",fontWeight=FontWeight.Bold,fontSize=22.sp);Text(trend.message,color=TitanTextSecondary);if(trend.entries>=2){Text("Cambio de peso: "+String.format("%.1f",trend.weightChangeKg)+" kg");Text("Ritmo aproximado: "+String.format("%.2f",trend.weeklyWeightRateKg)+" kg/semana",color=TitanTextSecondary);trend.waistChangeCm?.let{Text("Cambio de cintura: "+String.format("%.1f",it)+" cm",color=TitanTextSecondary)}}}};Spacer(Modifier.height(12.dp));entries.takeLast(5).reversed().forEach{e->Text(e.date+" · "+e.weightKg+" kg"+(e.waistCm?.let{" · cintura "+it+" cm"}?:""),color=TitanTextSecondary)};Spacer(Modifier.weight(1f));TextButton(back,Modifier.fillMaxWidth()){Text("Volver")}}}

@Composable private fun AddMeal(done:(String,Int)->Unit,back:()->Unit){var q by remember{mutableStateOf("")};var selected by remember{mutableStateOf<FoodItem?>(null)};var grams by remember{mutableStateOf("100")};Column(Modifier.padding(24.dp)){Header("AÑADIR COMIDA","Alimentos");Field("Buscar alimento",q){q=it};selected?.let{food->Text(food.name,fontWeight=FontWeight.Bold,fontSize=20.sp);Field("Cantidad (g)",grams){grams=it};val g=grams.toIntOrNull()?:100;Text(MealEngine.foodKcal(food,g).toString()+" kcal",color=TitanPrimary,fontWeight=FontWeight.Bold);PrimaryButton("Añadir a mi día"){done(food.name,MealEngine.foodKcal(food,g))};TextButton({selected=null}){Text("Cambiar alimento")}}?:run{MealEngine.searchFoods(q).take(8).forEach{food->Card(onClick={selected=food},colors=CardDefaults.cardColors(containerColor=TitanCard),modifier=Modifier.fillMaxWidth().padding(vertical=4.dp)){Row(Modifier.padding(14.dp)){Text(food.name,Modifier.weight(1f));Text(food.kcalPer100.toString()+" kcal/100g",color=TitanTextSecondary)}}}};Spacer(Modifier.weight(1f));TextButton(back,Modifier.fillMaxWidth()){Text("Volver")}}}
@Composable private fun SocialMealScreen(done:(String,Int)->Unit,back:()->Unit){var selected by remember{mutableStateOf<SocialMeal?>(null)};var amount by remember{mutableStateOf(SocialAmount.NORMAL)};Column(Modifier.padding(24.dp)){Header("COMIDAS SOCIALES","Estimación rápida");Text("No necesitas pesar. Elige una referencia y cuánto comiste.",color=TitanTextSecondary);selected?.let{meal->Text(meal.name,fontWeight=FontWeight.Bold,fontSize=24.sp);Row{SocialAmount.entries.forEach{a->FilterChip(amount==a,{amount=a},{Text(when(a){SocialAmount.LITTLE->"POCO";SocialAmount.NORMAL->"NORMAL";SocialAmount.A_LOT->"BASTANTE"})});Spacer(Modifier.width(6.dp))}};Text("Estimación: "+MealEngine.socialKcal(meal,amount)+" kcal",color=TitanPrimary,fontWeight=FontWeight.Bold);PrimaryButton("Añadir comida social"){done(meal.name,MealEngine.socialKcal(meal,amount))}}?:run{MealEngine.socialMeals.forEach{meal->Card(onClick={selected=meal},colors=CardDefaults.cardColors(containerColor=TitanCard),modifier=Modifier.fillMaxWidth().padding(vertical=5.dp)){Text(meal.name,Modifier.padding(18.dp),fontWeight=FontWeight.SemiBold)}}};Spacer(Modifier.weight(1f));TextButton(back,Modifier.fillMaxWidth()){Text("Volver")}}}
