package com.blsd.titan

import android.os.Bundle
import android.content.Context
import android.graphics.Typeface
import android.view.Gravity
import android.widget.Button
import android.widget.LinearLayout
import android.widget.ScrollView
import android.widget.TextView
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.animation.*
import androidx.compose.animation.core.*
import androidx.compose.foundation.clickable
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.layout.ContentScale

class MainActivity:ComponentActivity(){
 override fun onCreate(savedInstanceState:Bundle?){
  super.onCreate(savedInstanceState)
  enableEdgeToEdge()
  val diagnostics=getSharedPreferences(TitanApplication.CRASH_PREFS,Context.MODE_PRIVATE)
  val lastCrash=diagnostics.getString(TitanApplication.CRASH_KEY,null)
  if(lastCrash!=null){
   val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(32,48,32,32)}
   box.addView(TextView(this).apply{text="TITÁN — DIAGNÓSTICO DE ARRANQUE";textSize=20f;setTypeface(null,Typeface.BOLD)})
   box.addView(TextView(this).apply{text="Se detectó el cierre anterior. Este informe identifica el fallo exacto:\n\n$lastCrash";textSize=12f;setTextIsSelectable(true)},LinearLayout.LayoutParams(-1,0,1f))
   box.addView(Button(this).apply{text="REINTENTAR TITÁN";setOnClickListener{diagnostics.edit().remove(TitanApplication.CRASH_KEY).apply();recreate()}})
   setContentView(ScrollView(this).apply{addView(box)})
   return
  }
  setContent{TitanTheme{TitanApp()}}
 }
}
private enum class Screen{WELCOME,OBJECTIVE,PROFILE,WORK,WORK_DETAIL,TRAINING,MAINTENANCE,STRATEGY,TODAY,MEALS,DISH,ALTERNATIVES,INGREDIENT,DAY_CLOSE,WEEK,WEEK_REVIEW,BODY,ADD,SOCIAL}

@Composable fun TitanApp(){
 val context=LocalContext.current
 val store=remember{TitanStore(context)}
 val saved=remember{runCatching{store.load()}.getOrNull()}
 var screen by remember{mutableStateOf(if(saved!=null)Screen.TODAY else Screen.WELCOME)}
 var sex by remember{mutableStateOf(saved?.sex?:Sex.MALE)}
 var age by remember{mutableStateOf((saved?.age?:39).toString())};var height by remember{mutableStateOf((saved?.heightCm?:170.0).toInt().toString())};var weight by remember{mutableStateOf((saved?.weightKg?:93.0).toInt().toString())}
 var standing by remember{mutableStateOf("7")};var moving by remember{mutableStateOf("5")};var load by remember{mutableStateOf("2")};var breaks by remember{mutableStateOf("1")};var workIntensity by remember{mutableStateOf(WorkIntensity.MODERATE)};var variableDay by remember{mutableStateOf(true)}
 var sessions by remember{mutableStateOf("4")};var minutes by remember{mutableStateOf("75")};var trainingIntensity by remember{mutableStateOf(TrainingIntensity.HIGH)}
 var estimate by remember{mutableStateOf<EnergyEstimate?>(saved?.let{EnergyEstimate(0,0,0,0,it.maintenance)})};var strategy by remember{mutableStateOf(saved?.strategy?:Strategy.MODERATE)}
 var selectedMealId by remember{mutableStateOf<String?>(null)};var proposedDish by remember{mutableStateOf<Dish?>(null)};var selectedIngredient by remember{mutableStateOf(0)}
 var meals by remember{mutableStateOf(saved?.let{
  runCatching{
   val base=TitanEngine.plans(it.maintenance).firstOrNull{p->p.strategy==it.strategy} ?: TitanEngine.plans(it.maintenance).first()
   store.ensureToday(base.copy(target=store.activeTarget(base.target))).meals
  }.getOrElse{
   store.clear()
   emptyList()
  }
 }?:emptyList())}
 fun currentPlan():CaloriePlan{val m=estimate?.maintenance?:1;val plans=TitanEngine.plans(m);val base=plans.firstOrNull{it.strategy==strategy}?:plans.first();val target=store.activeTarget(base.target);return base.copy(target=target)}
 Surface(Modifier.fillMaxSize(),color=TitanBackground){
  Box(Modifier.fillMaxSize().windowInsetsPadding(WindowInsets.safeDrawing).imePadding().background(TitanBackground)){
  AnimatedContent(targetState=screen,transitionSpec={fadeIn(tween(260))+slideInHorizontally(tween(260)){it/10} togetherWith fadeOut(tween(180))},label="screen"){shownScreen->
  Box(Modifier.fillMaxSize()){TitanAtmosphere();
  when(shownScreen){
   Screen.WELCOME->Welcome{screen=Screen.OBJECTIVE}
   Screen.OBJECTIVE->Objective{screen=Screen.PROFILE}
   Screen.PROFILE->Profile(age,{age=it},height,{height=it},weight,{weight=it},sex,{sex=it}){screen=Screen.WORK}
   Screen.WORK->Work(standing,{standing=it},moving,{moving=it},load,{load=it}){screen=Screen.WORK_DETAIL}
   Screen.WORK_DETAIL->WorkDetail(breaks,{breaks=it},workIntensity,{workIntensity=it},variableDay,{variableDay=it}){screen=Screen.TRAINING}
   Screen.TRAINING->Training(sessions,{sessions=it},minutes,{minutes=it},trainingIntensity,{trainingIntensity=it}){
    val w=weight.toDoubleOrNull()?:70.0
    val qe=QuestionnaireEngine.energy(w,ActivityQuestionnaire(standing.toDoubleOrNull()?:0.0,moving.toDoubleOrNull()?:0.0,load.toDoubleOrNull()?:0.0,workIntensity,breaks.toDoubleOrNull()?:0.0,variableDay),TrainingQuestionnaire(sessions.toIntOrNull()?:0,minutes.toIntOrNull()?:0,trainingIntensity))
    estimate=TitanEngine.estimateEnergy(UserProfile(sex,age.toIntOrNull()?:30,height.toDoubleOrNull()?:170.0,w,1.2,qe.workDailyKcal,qe.trainingDailyKcal));screen=Screen.MAINTENANCE
   }
   Screen.MAINTENANCE->estimate?.let{Maintenance(it){screen=Screen.STRATEGY}}?:run{screen=Screen.TRAINING}
   Screen.STRATEGY->estimate?.let{safeEstimate->Strategies(safeEstimate.maintenance,strategy,{strategy=it}){
    val profile=UserProfile(sex,age.toIntOrNull()?:30,height.toDoubleOrNull()?:170.0,weight.toDoubleOrNull()?:70.0)
    store.save(profile,safeEstimate.maintenance,strategy)
    meals=TitanEngine.distribute(currentPlan().target,listOf("Desayuno","Comida","Merienda","Cena"));store.saveDay(meals,currentPlan());screen=Screen.TODAY}}?:run{screen=Screen.TRAINING}
   Screen.TODAY->{val p=currentPlan();Today(p,TitanEngine.balance(p,meals.sumOf{it.consumedKcal}),MealEngine.macroBalance(MealEngine.macroTarget(weight.toDoubleOrNull()?:70.0,p.target),meals),meals,{screen=Screen.MEALS},{id->val updated=meals.map{if(it.id==id)it.copy(status=MealStatus.SKIPPED)else it}.let(TitanEngine::redistribute);meals=updated;store.saveDay(updated,p)},{screen=Screen.DAY_CLOSE},{screen=Screen.WEEK},{screen=Screen.ADD},{screen=Screen.SOCIAL})}
   Screen.MEALS->MealList(meals,{m->selectedMealId=m.id;proposedDish=MealEngine.propose(m.plannedKcal);screen=Screen.DISH},{id->val updated=meals.map{if(it.id==id)it.copy(status=MealStatus.SKIPPED)else it}.let(TitanEngine::redistribute);meals=updated;store.saveDay(updated,currentPlan())},{screen=Screen.TODAY})
   Screen.DISH->proposedDish?.let{safeDish->DishProposal(safeDish,{screen=Screen.ALTERNATIVES},{index->selectedIngredient=index;screen=Screen.INGREDIENT},{
    val id=selectedMealId;val d=safeDish;val updated=meals.map{if(it.id==id)it.copy(name=d.name,consumedKcal=d.kcal,status=MealStatus.CONFIRMED,proteinG=d.proteinG,carbsG=d.carbsG,fatG=d.fatG)else it}.let(TitanEngine::redistribute);meals=updated;store.saveDay(updated,currentPlan());screen=Screen.MEALS
   },{screen=Screen.MEALS})}?:run{screen=Screen.MEALS}
   Screen.ALTERNATIVES->{val meal=meals.firstOrNull{it.id==selectedMealId};val dish=proposedDish;if(meal!=null&&dish!=null)Alternatives(meal.plannedKcal,dish,{d->proposedDish=d;screen=Screen.DISH},{screen=Screen.DISH}) else screen=Screen.MEALS}
   Screen.INGREDIENT->{
    val dish=proposedDish
    if(dish!=null && selectedIngredient in dish.ingredients.indices){
     IngredientEditor(dish,selectedIngredient,
      {g->proposedDish=proposedDish?.let{MealEngine.resizeIngredient(it,selectedIngredient,g)}},
      {replacement->proposedDish=proposedDish?.let{MealEngine.replaceIngredient(it,selectedIngredient,replacement)};screen=Screen.DISH},
      {screen=Screen.DISH})
    }else screen=Screen.MEALS
   }
   Screen.DAY_CLOSE->DayClose(TitanEngine.closeDay(currentPlan(),meals),store.remainingDaysInWeek()){store.saveDay(meals,currentPlan(),closed=true);screen=Screen.WEEK}
   Screen.WEEK->WeekHistory(store.weekHistory(),{screen=Screen.WEEK_REVIEW},{screen=Screen.BODY}){screen=Screen.TODAY}
   Screen.BODY->BodyProgress(store.bodyHistory(),{w,waist->store.saveBodyEntry(w,waist)},{screen=Screen.TODAY})
   Screen.WEEK_REVIEW->WeeklyReviewScreen(store.weekHistory(),currentPlan().target,{adjustment->store.applyWeeklyAdjustment(adjustment);val names=listOf("Desayuno","Comida","Merienda","Cena");meals=TitanEngine.distribute(adjustment.nextTarget,names);store.saveDay(meals,currentPlan());screen=Screen.TODAY},{screen=Screen.TODAY})
   Screen.SOCIAL->SocialMealScreen({name,kcal->val updated=meals+MealSlot("social-"+System.currentTimeMillis(),name,kcal,kcal,MealStatus.CONFIRMED);meals=updated;store.saveDay(updated,currentPlan());screen=Screen.TODAY},{screen=Screen.TODAY})
   Screen.ADD->AddMeal({n,k->val i=meals.indexOfFirst{it.status==MealStatus.PENDING};if(i>=0){val updated=meals.mapIndexed{x,m->if(x==i)m.copy(name=n,consumedKcal=k,status=MealStatus.CONFIRMED)else m}.let(TitanEngine::redistribute);meals=updated;store.saveDay(updated,currentPlan())};screen=Screen.TODAY}){screen=Screen.TODAY}
  }
  if(shownScreen!=Screen.WELCOME){TitanArrows(shownScreen,{screen=previousScreen(shownScreen)},{screen=nextScreen(shownScreen)})}
  }}
  }
 }
}
private fun previousScreen(s:Screen)=when(s){Screen.OBJECTIVE->Screen.WELCOME;Screen.PROFILE->Screen.OBJECTIVE;Screen.WORK->Screen.PROFILE;Screen.WORK_DETAIL->Screen.WORK;Screen.TRAINING->Screen.WORK_DETAIL;Screen.MAINTENANCE->Screen.TRAINING;Screen.STRATEGY->Screen.MAINTENANCE;Screen.TODAY->Screen.TODAY;Screen.MEALS->Screen.TODAY;Screen.DISH->Screen.MEALS;Screen.ALTERNATIVES->Screen.DISH;Screen.INGREDIENT->Screen.DISH;Screen.DAY_CLOSE->Screen.TODAY;Screen.WEEK->Screen.TODAY;Screen.WEEK_REVIEW->Screen.WEEK;Screen.BODY->Screen.WEEK;Screen.ADD->Screen.TODAY;Screen.SOCIAL->Screen.ADD;else->s}
private fun nextScreen(s:Screen)=when(s){Screen.TODAY->Screen.MEALS;Screen.MEALS->Screen.ADD;Screen.ADD->Screen.SOCIAL;Screen.WEEK->Screen.BODY;else->s}
@Composable private fun TitanArrows(s:Screen,back:()->Unit,next:()->Unit){Row(Modifier.fillMaxWidth().padding(horizontal=18.dp,vertical=12.dp),horizontalArrangement=Arrangement.SpaceBetween){Text("‹",fontSize=38.sp,color=TitanText,modifier=Modifier.clickable{back()}.padding(8.dp));val n=nextScreen(s);Text("›",fontSize=38.sp,color=if(n!=s)TitanPrimary else TitanDivider,modifier=Modifier.clickable(enabled=n!=s){next()}.padding(8.dp))}}
@Composable private fun TitanAtmosphere(){ /* Master UI uses clean graphite surfaces; photographic atmosphere is screen-specific. */ }
@Composable private fun TitanMark(){
 Column(Modifier.width(154.dp).height(100.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){
  Text("TITÁN",fontSize=34.sp,fontWeight=FontWeight.Black,letterSpacing=3.sp,color=TitanText)
  Text("RECOMPOSITION",fontSize=9.sp,fontWeight=FontWeight.Bold,letterSpacing=2.sp,color=TitanPrimary)
 }
}
@Composable private fun FoodVisual(modifier:Modifier=Modifier){Canvas(modifier.clip(RoundedCornerShape(18.dp)).background(Brush.linearGradient(listOf(Color(0xFF25323A),Color(0xFF0D151B))))){val w=size.width;val h=size.height;drawCircle(Color(0xFF11191E),w*.36f,Offset(w*.50f,h*.52f));drawCircle(Color(0xFFD9C49A),w*.26f,Offset(w*.50f,h*.52f));drawCircle(Color(0xFF4CAF7A),w*.11f,Offset(w*.39f,h*.43f));drawCircle(Color(0xFFE6B85C),w*.10f,Offset(w*.60f,h*.43f));drawCircle(Color(0xFFB66D52),w*.11f,Offset(w*.48f,h*.62f));drawCircle(Color(0xFFF1E3C6),w*.08f,Offset(w*.64f,h*.61f));drawCircle(TitanPrimary.copy(alpha=.16f),w*.55f,Offset(w*.5f,h*.5f))}}
@Composable private fun Welcome(next:()->Unit){val pulse=rememberInfiniteTransition(label="hero");val glow by pulse.animateFloat(.72f,1f,infiniteRepeatable(tween(1800),RepeatMode.Reverse),label="glow");Box(Modifier.fillMaxSize()){Canvas(Modifier.fillMaxSize()){val w=size.width;val h=size.height;drawCircle(TitanPrimary.copy(alpha=.08f*glow),w*.7f,Offset(w*.5f,h*.18f));drawLine(TitanText.copy(alpha=.16f),Offset(0f,h*.67f),Offset(w*.24f,h*.52f),4f);drawLine(TitanText.copy(alpha=.16f),Offset(w*.24f,h*.52f),Offset(w*.44f,h*.66f),4f);drawLine(TitanText.copy(alpha=.12f),Offset(w*.35f,h*.66f),Offset(w*.68f,h*.43f),4f);drawLine(TitanText.copy(alpha=.12f),Offset(w*.68f,h*.43f),Offset(w,h*.65f),4f)};Column(Modifier.fillMaxSize().padding(28.dp),verticalArrangement=Arrangement.SpaceBetween,horizontalAlignment=Alignment.CenterHorizontally){Column(Modifier.padding(top=54.dp),horizontalAlignment=Alignment.CenterHorizontally){TitanMark();Text("T I T Á N",style=MaterialTheme.typography.headlineLarge);Text("DATOS QUE TE LLEVAN MÁS LEJOS",style=MaterialTheme.typography.labelLarge,color=TitanPrimary);Spacer(Modifier.height(52.dp));Text("MÁS QUE UNA APP.\nUN MÉTODO.",style=MaterialTheme.typography.headlineMedium,textAlign=TextAlign.Center,lineHeight=34.sp);Spacer(Modifier.height(18.dp));Text("NUTRICIÓN INTELIGENTE  •  RENDIMIENTO REAL\nHÁBITOS SOSTENIBLES  •  TU MEJOR VERSIÓN",color=TitanTextSecondary,textAlign=TextAlign.Center,lineHeight=22.sp,fontSize=12.sp)};Column(Modifier.fillMaxWidth()){Text("DISCIPLINA HOY. RESULTADOS MAÑANA.",style=MaterialTheme.typography.labelLarge,color=TitanTextSecondary,modifier=Modifier.fillMaxWidth(),textAlign=TextAlign.Center);Spacer(Modifier.height(14.dp));PrimaryButton("COMENZAR",next)}}}}
@Composable private fun Header(step:String,title:String){Spacer(Modifier.height(TitanDimens.ScreenTop));Text(step,color=TitanTextSecondary,style=MaterialTheme.typography.labelMedium);Spacer(Modifier.height(8.dp));Text(title,style=MaterialTheme.typography.headlineMedium);Spacer(Modifier.height(14.dp))}
@Composable private fun Field(label:String,value:String,set:(String)->Unit){OutlinedTextField(value,{set(it.filter(Char::isDigit))},label={Text(label)},modifier=Modifier.fillMaxWidth().padding(vertical=5.dp),shape=RoundedCornerShape(TitanDimens.CardRadius),colors=OutlinedTextFieldDefaults.colors(focusedBorderColor=TitanPrimary,unfocusedBorderColor=TitanStroke,focusedContainerColor=TitanSurface,unfocusedContainerColor=TitanSurface))}
@Composable private fun TextFieldInput(label:String,value:String,set:(String)->Unit){OutlinedTextField(value,set,label={Text(label)},modifier=Modifier.fillMaxWidth().padding(vertical=5.dp),colors=OutlinedTextFieldDefaults.colors(focusedBorderColor=TitanPrimary,unfocusedBorderColor=TitanDivider))}
@Composable private fun PrimaryButton(label:String,go:()->Unit){Button(go,Modifier.fillMaxWidth().height(56.dp),shape=RoundedCornerShape(TitanDimens.ButtonRadius),colors=ButtonDefaults.buttonColors(containerColor=TitanPrimary,contentColor=TitanBackground),elevation=ButtonDefaults.buttonElevation(defaultElevation=7.dp,pressedElevation=2.dp)){Text(label.uppercase(),fontWeight=FontWeight.ExtraBold,letterSpacing=.8.sp)}}
@Composable private fun Objective(next:()->Unit){var selected by remember{mutableStateOf("Recomposición corporal")};val options=listOf("Recomposición corporal" to "Perder grasa y construir una versión más fuerte de ti.","Rendimiento deportivo" to "Alimenta el entrenamiento y mejora tu rendimiento.","Salud y bienestar" to "Construye hábitos sostenibles para sentirte mejor.","Otro objetivo" to "Configura TITÁN alrededor de una prioridad diferente.");Column(Modifier.padding(horizontal=24.dp)){Header("Paso 1 de 6","¿Cuál es tu objetivo principal?");Text("Selecciona el que mejor se adapta a ti en este momento.",color=TitanTextSecondary);Spacer(Modifier.height(14.dp));options.forEach{(title,desc)->Card(onClick={selected=title},modifier=Modifier.fillMaxWidth().padding(vertical=6.dp),shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=if(selected==title)TitanPrimary.copy(alpha=.13f) else TitanCard),border=if(selected==title)androidx.compose.foundation.BorderStroke(1.dp,TitanPrimary) else null){Row(Modifier.padding(17.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(title.uppercase(),fontWeight=FontWeight.ExtraBold);Text(desc,color=TitanTextSecondary,fontSize=12.sp)};Text(if(selected==title)"✓" else "○",color=if(selected==title)TitanPrimary else TitanTextSecondary,fontSize=22.sp)}}};Spacer(Modifier.weight(1f));PrimaryButton("CONTINUAR",next)}}
@Composable private fun Profile(age:String,setAge:(String)->Unit,height:String,setHeight:(String)->Unit,weightValue:String,setWeight:(String)->Unit,sex:Sex,setSex:(Sex)->Unit,next:()->Unit){Column(Modifier.padding(24.dp)){Header("Paso 2 de 6","Tus datos");Row{FilterChip(sex==Sex.MALE,{setSex(Sex.MALE)},{Text("Hombre")});Spacer(Modifier.width(8.dp));FilterChip(sex==Sex.FEMALE,{setSex(Sex.FEMALE)},{Text("Mujer")})};Field("Edad",age,setAge);Field("Altura (cm)",height,setHeight);Field("Peso (kg)",weightValue,setWeight);Spacer(Modifier.weight(1f));PrimaryButton("Continuar",next)}}
@Composable private fun Work(a:String,sa:(String)->Unit,b:String,sb:(String)->Unit,c:String,sc:(String)->Unit,next:()->Unit){Column(Modifier.padding(24.dp)){Header("Paso 3 de 6","Tu actividad diaria");Text("Queremos medir tu día real, no asignarte una etiqueta genérica.",color=TitanTextSecondary);Field("Horas de pie",a,sa);Field("Horas en movimiento",b,sb);Field("Horas con cargas / trabajo físico",c,sc);Spacer(Modifier.weight(1f));PrimaryButton("Continuar",next)}}
@Composable private fun WorkDetail(breaks:String,setBreaks:(String)->Unit,intensity:WorkIntensity,setIntensity:(WorkIntensity)->Unit,variable:Boolean,setVariable:(Boolean)->Unit,next:()->Unit){Column(Modifier.padding(24.dp)){Header("Paso 4 de 6","Cómo es tu jornada");Field("Horas totales de pausas",breaks,setBreaks);Text("Intensidad habitual",color=TitanTextSecondary);Row{WorkIntensity.entries.forEach{v->FilterChip(intensity==v,{setIntensity(v)},{Text(when(v){WorkIntensity.LOW->"Baja";WorkIntensity.MODERATE->"Media";WorkIntensity.HIGH->"Alta"})});Spacer(Modifier.width(6.dp))}};Spacer(Modifier.height(12.dp));Text("¿Tu actividad cambia mucho de un día a otro?",color=TitanTextSecondary);Row{FilterChip(variable,{setVariable(true)},{Text("Sí")});Spacer(Modifier.width(8.dp));FilterChip(!variable,{setVariable(false)},{Text("No")})};Spacer(Modifier.weight(1f));PrimaryButton("Continuar",next)}}
@Composable private fun Training(a:String,sa:(String)->Unit,b:String,sb:(String)->Unit,intensity:TrainingIntensity,setIntensity:(TrainingIntensity)->Unit,next:()->Unit){Column(Modifier.padding(24.dp)){Header("Paso 5 de 6","Tu entrenamiento");Text("Frecuencia, duración e intensidad alimentan la estimación inicial.",color=TitanTextSecondary);Field("Sesiones por semana",a,sa);Field("Minutos por sesión",b,sb);Text("Intensidad habitual",color=TitanTextSecondary);Row{TrainingIntensity.entries.forEach{v->FilterChip(intensity==v,{setIntensity(v)},{Text(when(v){TrainingIntensity.LIGHT->"Suave";TrainingIntensity.MODERATE->"Media";TrainingIntensity.HIGH->"Alta"})});Spacer(Modifier.width(6.dp))}};Spacer(Modifier.weight(1f));PrimaryButton("Calcular mantenimiento",next)}}
@Composable private fun Maintenance(e:EnergyEstimate,next:()->Unit){var details by remember{mutableStateOf(false)};Column(Modifier.padding(horizontal=22.dp)){Header("Paso 6 de 6","Tu mantenimiento");Text("Según tus datos, tu gasto energético diario estimado es:",color=TitanTextSecondary);Spacer(Modifier.height(16.dp));Card(colors=CardDefaults.cardColors(containerColor=TitanCard),shape=RoundedCornerShape(22.dp)){Column(Modifier.fillMaxWidth().padding(22.dp)){Text(e.maintenance.toString()+" kcal",fontSize=38.sp,fontWeight=FontWeight.Bold);Text("VER CÓMO SE CALCULÓ "+if(details)"⌃" else "›",color=TitanPrimary,fontWeight=FontWeight.Bold,modifier=Modifier.clickable{details=!details}.padding(vertical=8.dp));AnimatedVisibility(details){Column{Text("GASTO BASAL  "+e.bmr+" kcal",color=TitanTextSecondary);Text("ACTIVIDAD BASE  "+e.baseWithActivity+" kcal",color=TitanTextSecondary);Text("TRABAJO  "+e.dailyActivityKcal+" kcal",color=TitanTextSecondary);Text("ENTRENAMIENTO  "+e.trainingKcal+" kcal",color=TitanTextSecondary)}}}};Spacer(Modifier.weight(1f));PrimaryButton("Elegir estrategia",next)}}
@Composable private fun Strategies(m:Int,current:Strategy,set:(Strategy)->Unit,next:()->Unit){Column(Modifier.padding(24.dp)){Header("Configuración inicial","Elige tu estrategia");TitanEngine.plans(m).forEach{p->Card(onClick={set(p.strategy)},modifier=Modifier.fillMaxWidth().padding(vertical=6.dp),colors=CardDefaults.cardColors(containerColor=if(p.strategy==current)TitanCard else TitanSurface)){Column(Modifier.padding(18.dp)){Text(when(p.strategy){Strategy.LOW->"Bajo";Strategy.MODERATE->"Moderado";Strategy.RIGOROUS->"Riguroso"},fontWeight=FontWeight.Bold);Text(p.target.toString()+" kcal · margen hasta "+p.toleranceCeiling,color=TitanTextSecondary)}}};Spacer(Modifier.weight(1f));PrimaryButton("Entrar en TITÁN",next)}}
@Composable private fun RowScope.MacroBar(label:String,value:Int,target:Int){val goal=if(target>0)(value.toFloat()/target).coerceIn(0f,1f) else 0f;val progress by animateFloatAsState(goal,tween(750),label="macro");Column(Modifier.weight(1f)){Text(label,style=MaterialTheme.typography.labelLarge);Text("$value / $target g",color=TitanTextSecondary,fontSize=12.sp);LinearProgressIndicator(progress={progress},modifier=Modifier.fillMaxWidth().height(5.dp),color=TitanSecondary,trackColor=TitanDivider)}}
@Composable private fun CalorieRing(b:DailyBalance,plan:CaloriePlan){val goal=(b.consumed/plan.target.toFloat()).coerceIn(0f,1f);val progress by animateFloatAsState(goal,tween(900,easing=FastOutSlowInEasing),label="calorieRing");Box(Modifier.size(210.dp),contentAlignment=Alignment.Center){Canvas(Modifier.fillMaxSize()){val stroke=18.dp.toPx();drawArc(TitanDivider,-90f,360f,false,style=Stroke(stroke,cap=StrokeCap.Round));drawArc(TitanPrimary,-90f,360f*progress,false,style=Stroke(stroke,cap=StrokeCap.Round))};Column(horizontalAlignment=Alignment.CenterHorizontally){Text("Te quedan",color=TitanTextSecondary);Text(b.availableToTarget.toString(),fontSize=42.sp,fontWeight=FontWeight.Bold);Text("kcal",color=TitanTextSecondary)}}}
@Composable private fun BottomNav(today:()->Unit,plan:()->Unit,progress:()->Unit,more:()->Unit){NavigationBar(containerColor=TitanSurface.copy(alpha=.97f),tonalElevation=10.dp){NavigationBarItem(true,today,{Text("●",color=TitanPrimary)},label={Text("HOY",fontWeight=FontWeight.Bold)},colors=NavigationBarItemDefaults.colors(indicatorColor=TitanPrimary.copy(alpha=.14f),selectedTextColor=TitanPrimary));NavigationBarItem(false,plan,{Text("◆")},label={Text("PLAN")});NavigationBarItem(false,progress,{Text("▲")},label={Text("PROGRESO")});NavigationBarItem(false,more,{Text("•••")},label={Text("MÁS")})}}
@Composable private fun Today(plan:CaloriePlan,b:DailyBalance,macros:MacroBalance,meals:List<MealSlot>,add:()->Unit,skip:(String)->Unit,close:()->Unit,week:()->Unit,quick:()->Unit,social:()->Unit){Scaffold(containerColor=Color.Transparent,bottomBar={BottomNav({},add,week,{})}){pad->Column(Modifier.padding(pad).padding(horizontal=22.dp)){Spacer(Modifier.height(58.dp));Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("HOY",style=MaterialTheme.typography.headlineLarge,fontWeight=FontWeight.ExtraBold);Text(java.time.LocalDate.now().toString().uppercase(),color=TitanPrimary,style=MaterialTheme.typography.labelLarge)};Surface(shape=RoundedCornerShape(18.dp),color=TitanCard){Text("DÍA ACTIVO",Modifier.padding(horizontal=12.dp,vertical=7.dp),color=TitanSuccess,fontSize=11.sp,fontWeight=FontWeight.Bold)}};Spacer(Modifier.height(14.dp));Card(colors=CardDefaults.cardColors(containerColor=TitanCard.copy(alpha=.82f)),shape=RoundedCornerShape(26.dp)){Column(Modifier.padding(18.dp)){Box(Modifier.fillMaxWidth(),contentAlignment=Alignment.Center){CalorieRing(b,plan)};Spacer(Modifier.height(14.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp)){MacroBar("PROTEÍNA",macros.proteinG,macros.target.proteinG);MacroBar("CARBOS",macros.carbsG,macros.target.carbsG);MacroBar("GRASAS",macros.fatG,macros.target.fatG)}}};Spacer(Modifier.height(16.dp));Text("TU PLAN DE HOY",fontWeight=FontWeight.Bold,letterSpacing=1.sp);Spacer(Modifier.height(8.dp));meals.take(2).forEach{m->Surface(shape=RoundedCornerShape(16.dp),color=TitanSurface.copy(alpha=.9f),modifier=Modifier.fillMaxWidth().padding(vertical=4.dp)){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(38.dp).background(if(m.status==MealStatus.CONFIRMED)TitanSuccess.copy(alpha=.18f) else TitanPrimary.copy(alpha=.12f),RoundedCornerShape(12.dp)),contentAlignment=Alignment.Center){Text(if(m.status==MealStatus.CONFIRMED)"✓" else "•",color=if(m.status==MealStatus.CONFIRMED)TitanSuccess else TitanPrimary,fontWeight=FontWeight.Bold)};Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(m.name,fontWeight=FontWeight.SemiBold);Text(m.plannedKcal.toString()+" KCAL",color=TitanTextSecondary,fontSize=12.sp)};Text(m.status.name,color=TitanTextSecondary,fontSize=10.sp)}}};Spacer(Modifier.height(12.dp));PrimaryButton("VER MIS COMIDAS",add);Spacer(Modifier.height(9.dp));Row(Modifier.fillMaxWidth()){OutlinedButton(quick,Modifier.weight(1f),shape=RoundedCornerShape(14.dp)){Text("+ ALIMENTO",fontSize=12.sp)};Spacer(Modifier.width(8.dp));OutlinedButton(social,Modifier.weight(1f),shape=RoundedCornerShape(14.dp)){Text("SOCIAL",fontSize=12.sp)}};TextButton(close,Modifier.fillMaxWidth()){Text("CERRAR DÍA",color=TitanTextSecondary)}}}}
@Composable private fun MealList(meals:List<MealSlot>,open:(MealSlot)->Unit,skip:(String)->Unit,back:()->Unit){Column(Modifier.padding(horizontal=22.dp)){Header("PLAN DE HOY","Mis comidas");Text("TU DÍA, ORGANIZADO SIN CONVERTIRLO EN UNA CÁRCEL.",color=TitanTextSecondary,fontSize=12.sp,letterSpacing=.6.sp);Spacer(Modifier.height(12.dp));meals.forEachIndexed{i,m->Card(onClick={if(m.status==MealStatus.PENDING)open(m)},colors=CardDefaults.cardColors(containerColor=TitanCard.copy(alpha=.9f)),shape=RoundedCornerShape(22.dp),modifier=Modifier.fillMaxWidth().padding(vertical=6.dp)){Row(Modifier.padding(15.dp),verticalAlignment=Alignment.CenterVertically){FoodVisual(Modifier.size(64.dp));Spacer(Modifier.width(14.dp));Column(Modifier.weight(1f)){Text(m.name.uppercase(),fontWeight=FontWeight.ExtraBold);Text(m.plannedKcal.toString()+" KCAL OBJETIVO",color=TitanTextSecondary,fontSize=11.sp);Spacer(Modifier.height(5.dp));Text(when(m.status){MealStatus.PENDING->"PENDIENTE";MealStatus.CONFIRMED->"✓ CONFIRMADA · "+m.consumedKcal+" KCAL";MealStatus.SKIPPED->"OMITIDA"},color=when(m.status){MealStatus.CONFIRMED->TitanSuccess;MealStatus.SKIPPED->TitanWarning;else->TitanPrimary},fontSize=11.sp,fontWeight=FontWeight.Bold)};if(m.status==MealStatus.PENDING)TextButton({skip(m.id)}){Text("OMITIR",fontSize=10.sp)}}}};Spacer(Modifier.weight(1f));TextButton(back,Modifier.fillMaxWidth()){Text("VOLVER A HOY")}}}
@Composable private fun DishProposal(d:Dish,change:()->Unit,ingredient:(Int)->Unit,confirm:()->Unit,back:()->Unit){Column(Modifier.padding(horizontal=22.dp)){Header("PLATO PROPUESTO",d.name);Card(colors=CardDefaults.cardColors(containerColor=TitanCard.copy(alpha=.92f)),shape=RoundedCornerShape(24.dp)){Column(Modifier.padding(20.dp)){FoodVisual(Modifier.fillMaxWidth().height(170.dp));Spacer(Modifier.height(16.dp));Text(d.kcal.toString()+" kcal",fontSize=30.sp,fontWeight=FontWeight.Bold);Text("Proteínas "+d.proteinG+" g · Carbohidratos "+d.carbsG+" g · Grasas "+d.fatG+" g",color=TitanTextSecondary);Spacer(Modifier.height(14.dp));d.ingredients.forEachIndexed{i,x->Row(Modifier.fillMaxWidth().padding(vertical=5.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(x.name,fontWeight=FontWeight.SemiBold);Text(x.grams.toString()+" g · "+x.kcal+" kcal",color=TitanTextSecondary)};TextButton({ingredient(i)}){Text("CAMBIAR")}}}};Spacer(Modifier.height(18.dp));PrimaryButton("CONFIRMAR PLATO",confirm);OutlinedButton(change,Modifier.fillMaxWidth().padding(top=10.dp)){Text("CAMBIAR PLATO")};TextButton(back,Modifier.fillMaxWidth()){Text("Atrás")}}}}
@Composable private fun Alternatives(target:Int,current:Dish,choose:(Dish)->Unit,back:()->Unit){
 Column(Modifier.padding(horizontal=22.dp)){
  Header("CAMBIAR PLATO","4 alternativas compatibles")
  MealEngine.alternatives(target,exclude=setOf(current.id)).forEach{d->
   Card(onClick={choose(d)},colors=CardDefaults.cardColors(containerColor=TitanCard.copy(alpha=.92f)),modifier=Modifier.fillMaxWidth().padding(vertical=5.dp)){
    Column(Modifier.padding(16.dp)){
     Text(d.name,fontWeight=FontWeight.Bold)
     Text(d.kcal.toString()+" kcal · P "+d.proteinG+" · C "+d.carbsG+" · G "+d.fatG,color=TitanTextSecondary)
    }
   }
  }
  Text("VER MÁS",color=TitanPrimary,modifier=Modifier.padding(16.dp))
  Spacer(Modifier.weight(1f))
  TextButton(back,Modifier.fillMaxWidth()){Text("VOLVER")}
 }
}

@Composable private fun IngredientEditor(d:Dish,index:Int,resize:(Int)->Unit,replace:(Ingredient)->Unit,back:()->Unit){val item=d.ingredients.getOrNull(index);if(item==null){LaunchedEffect(Unit){back()};return};var grams by remember(item.id,item.grams){mutableStateOf(item.grams.toString())};Column(Modifier.padding(horizontal=22.dp)){Header("INGREDIENTE",item.name);Text("Cambiar cantidad",color=TitanTextSecondary);Field("Gramos",grams){grams=it;it.toIntOrNull()?.let(resize)};Spacer(Modifier.height(16.dp));Text("Sustituir por",fontWeight=FontWeight.Bold);MealEngine.ingredientAlternatives(d,index).forEach{x->Card(onClick={replace(x)},colors=CardDefaults.cardColors(containerColor=TitanCard.copy(alpha=.92f)),modifier=Modifier.fillMaxWidth().padding(vertical=5.dp)){Row(Modifier.padding(16.dp)){Text(x.name,Modifier.weight(1f));Text(x.kcal.toString()+" kcal",color=TitanTextSecondary)}}};Spacer(Modifier.weight(1f));Text("El cambio mantiene aproximadamente el aporte energético del ingrediente original.",color=TitanTextSecondary,fontSize=12.sp);TextButton(back,Modifier.fillMaxWidth()){Text("VOLVER AL PLATO")}}}

@Composable private fun DayClose(r:DayCloseResult,remainingDays:Int,back:()->Unit){val recal=TitanEngine.weeklyRecalibration(r.excessToRecalibrate,remainingDays);Column(Modifier.padding(horizontal=22.dp)){Header("CIERRE DIARIO","Así termina tu día");Card(colors=CardDefaults.cardColors(containerColor=TitanCard),shape=RoundedCornerShape(22.dp)){Column(Modifier.padding(20.dp)){Text(r.consumed.toString()+" kcal",fontSize=36.sp,fontWeight=FontWeight.Bold);Text("Objetivo "+r.target+" · margen TITÁN "+r.toleranceCeiling,color=TitanTextSecondary);Spacer(Modifier.height(14.dp));Text(r.completedMeals.toString()+" comidas confirmadas · "+r.skippedMeals+" omitidas",color=TitanTextSecondary);Spacer(Modifier.height(14.dp));if(r.excessToRecalibrate==0)Text("Día dentro del margen. No hay compensación.",color=TitanSuccess,fontWeight=FontWeight.Bold)else{Text("Exceso sobre el margen: "+r.excessToRecalibrate+" kcal",color=TitanWarning,fontWeight=FontWeight.Bold);Text("Recalibración orientativa: "+recal.adjustmentPerDay+" kcal/día durante "+remainingDays+" días.",color=TitanTextSecondary)}}};Spacer(Modifier.height(18.dp));Text("TITÁN compensa únicamente lo que supera tu margen, no una desviación normal del objetivo.",color=TitanTextSecondary);Spacer(Modifier.weight(1f));PrimaryButton("Continuar",back)}}

@Composable private fun WeekHistory(days:List<DayRecord>,review:()->Unit,body:()->Unit,back:()->Unit){Column(Modifier.padding(horizontal=22.dp)){Header("PROGRESO","Mi semana");if(days.isEmpty())Text("Aún no hay días registrados esta semana.",color=TitanTextSecondary)else{days.forEach{d->Card(colors=CardDefaults.cardColors(containerColor=TitanCard),modifier=Modifier.fillMaxWidth().padding(vertical=4.dp)){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(d.date,fontWeight=FontWeight.Bold);Text(d.consumed.toString()+" / "+d.target+" kcal",color=TitanTextSecondary)};Text(if(d.closed)"CERRADO" else "EN CURSO",color=if(d.closed)TitanSuccess else TitanWarning)}};val avg=days.map{it.consumed}.average().toInt();val excess=days.sumOf{it.excess};Spacer(Modifier.height(16.dp));Text("Media registrada: "+avg+" kcal/día",fontWeight=FontWeight.Bold);Text("Exceso acumulado sobre tolerancia: "+excess+" kcal",color=TitanTextSecondary)}};Spacer(Modifier.weight(1f));if(days.isNotEmpty())PrimaryButton("Revisión semanal",review);OutlinedButton(body,Modifier.fillMaxWidth().padding(top=8.dp)){Text("Progreso corporal")};TextButton(back,Modifier.fillMaxWidth()){Text("Volver a Hoy")}}}

@Composable private fun Score(label:String,value:Int,set:(Int)->Unit){Column(Modifier.padding(vertical=5.dp)){Text(label,fontWeight=FontWeight.SemiBold);Row{(1..5).forEach{n->FilterChip(value==n,{set(n)},{Text(n.toString())});Spacer(Modifier.width(5.dp))}}}}
@Composable private fun WeeklyReviewScreen(days:List<DayRecord>,currentTarget:Int,apply:(WeeklyAdjustment)->Unit,back:()->Unit){var hunger by remember{mutableStateOf(3)};var energy by remember{mutableStateOf(3)};var recovery by remember{mutableStateOf(3)};var performance by remember{mutableStateOf(3)};var stress by remember{mutableStateOf(3)};var satisfaction by remember{mutableStateOf(3)};var done by remember{mutableStateOf(false)};val review=TitanEngine.weeklyReview(days,WeeklyFeedback(hunger,energy,recovery,performance,stress,satisfaction));val adjustment=TitanEngine.weeklyAdjustment(review,currentTarget);Column(Modifier.padding(horizontal=22.dp)){Header("REVISIÓN SEMANAL","Cómo ha ido tu semana");if(!done){Score("Hambre",hunger){hunger=it};Score("Energía",energy){energy=it};Score("Recuperación",recovery){recovery=it};Score("Rendimiento",performance){performance=it};Score("Estrés",stress){stress=it};Score("Satisfacción",satisfaction){satisfaction=it};Spacer(Modifier.weight(1f));PrimaryButton("Analizar semana"){done=true}}else{Card(colors=CardDefaults.cardColors(containerColor=TitanCard),shape=RoundedCornerShape(22.dp)){Column(Modifier.padding(20.dp)){Text("Resumen",fontSize=24.sp,fontWeight=FontWeight.Bold);Text("Media diaria: "+review.averageKcal+" kcal",color=TitanTextSecondary);Text("Adherencia aproximada: "+review.adherencePercent+"%",color=TitanTextSecondary);Text("Exceso sobre tolerancia: "+review.excessOverTolerance+" kcal",color=TitanTextSecondary);Spacer(Modifier.height(16.dp));Text(if(adjustment.delta==0)"Objetivo sin cambios" else "Nuevo objetivo: "+adjustment.nextTarget+" kcal",fontWeight=FontWeight.Bold,color=TitanPrimary);Text(adjustment.reason,color=TitanTextSecondary)}};Spacer(Modifier.weight(1f));if(adjustment.delta!=0)PrimaryButton("Aplicar ajuste"){apply(adjustment)} else PrimaryButton("Mantener objetivo"){apply(adjustment)};TextButton(back,Modifier.fillMaxWidth()){Text("Volver sin aplicar")}}}}

@Composable private fun BodyProgress(entries:List<BodyEntry>,save:(Double,Double?)->Unit,back:()->Unit){var weight by remember{mutableStateOf("")};var waist by remember{mutableStateOf("")};var refresh by remember{mutableStateOf(0)};val trend=TitanEngine.bodyTrend(entries);Column(Modifier.padding(horizontal=22.dp)){Header("PROGRESO","Composición corporal");Text("Registra peso y cintura. TITÁN usará la tendencia, no un dato aislado.",color=TitanTextSecondary);Field("Peso (kg)",weight){weight=it};Field("Cintura (cm, opcional)",waist){waist=it};Button({weight.toDoubleOrNull()?.let{save(it,waist.toDoubleOrNull());refresh++}},Modifier.fillMaxWidth(),colors=ButtonDefaults.buttonColors(containerColor=TitanPrimary,contentColor=TitanBackground)){Text("Guardar registro",fontWeight=FontWeight.Bold)};Spacer(Modifier.height(18.dp));Card(colors=CardDefaults.cardColors(containerColor=TitanCard),shape=RoundedCornerShape(22.dp)){Column(Modifier.padding(18.dp)){Text("Tendencia",fontWeight=FontWeight.Bold,fontSize=22.sp);Text(trend.message,color=TitanTextSecondary);if(trend.entries>=2){Text("Cambio de peso: "+String.format("%.1f",trend.weightChangeKg)+" kg");Text("Ritmo aproximado: "+String.format("%.2f",trend.weeklyWeightRateKg)+" kg/semana",color=TitanTextSecondary);trend.waistChangeCm?.let{Text("Cambio de cintura: "+String.format("%.1f",it)+" cm",color=TitanTextSecondary)}}}};Spacer(Modifier.height(12.dp));entries.takeLast(5).reversed().forEach{e->Text(e.date+" · "+e.weightKg+" kg"+(e.waistCm?.let{" · cintura "+it+" cm"}?:""),color=TitanTextSecondary)};Spacer(Modifier.weight(1f));TextButton(back,Modifier.fillMaxWidth()){Text("Volver")}}}

@Composable private fun AddMeal(done:(String,Int)->Unit,back:()->Unit){var q by remember{mutableStateOf("")};var selected by remember{mutableStateOf<FoodItem?>(null)};var grams by remember{mutableStateOf("100")};Column(Modifier.padding(horizontal=22.dp)){Header("NUTRICIÓN","Añadir comida");Row(Modifier.fillMaxWidth()){Surface(shape=RoundedCornerShape(18.dp),color=TitanPrimary.copy(alpha=.16f)){Text("ALIMENTOS",Modifier.padding(horizontal=16.dp,vertical=9.dp),color=TitanPrimary,fontWeight=FontWeight.Bold)};Spacer(Modifier.width(8.dp));Surface(shape=RoundedCornerShape(18.dp),color=TitanSurface){Text("COMIDAS SOCIALES",Modifier.padding(horizontal=16.dp,vertical=9.dp),color=TitanTextSecondary,fontWeight=FontWeight.Bold,fontSize=11.sp)}};Spacer(Modifier.height(10.dp));TextFieldInput("Buscar alimento",q){q=it};selected?.let{food->Card(colors=CardDefaults.cardColors(containerColor=TitanCard),shape=RoundedCornerShape(24.dp),modifier=Modifier.fillMaxWidth().padding(top=8.dp)){Column(Modifier.padding(18.dp)){FoodVisual(Modifier.fillMaxWidth().height(150.dp));Spacer(Modifier.height(14.dp));Text(food.name.uppercase(),fontWeight=FontWeight.ExtraBold,fontSize=21.sp);Field("Cantidad (g)",grams){grams=it};val g=grams.toIntOrNull()?:100;Text(MealEngine.foodKcal(food,g).toString()+" KCAL",color=TitanPrimary,fontWeight=FontWeight.ExtraBold,fontSize=24.sp);Spacer(Modifier.height(10.dp));PrimaryButton("AÑADIR A MI DÍA"){done(food.name,MealEngine.foodKcal(food,g))};TextButton({selected=null},Modifier.fillMaxWidth()){Text("CAMBIAR ALIMENTO")}}}}?:run{Text("RESULTADOS",fontSize=11.sp,color=TitanTextSecondary,fontWeight=FontWeight.Bold);MealEngine.searchFoods(q).take(8).forEachIndexed{i,food->Card(onClick={selected=food},colors=CardDefaults.cardColors(containerColor=TitanCard.copy(alpha=.9f)),shape=RoundedCornerShape(18.dp),modifier=Modifier.fillMaxWidth().padding(vertical=4.dp)){Row(Modifier.padding(12.dp),verticalAlignment=Alignment.CenterVertically){FoodVisual(Modifier.size(48.dp));Spacer(Modifier.width(12.dp));Text(food.name,Modifier.weight(1f),fontWeight=FontWeight.SemiBold);Text(food.kcalPer100.toString()+" kcal",color=TitanTextSecondary,fontSize=12.sp)}}}};Spacer(Modifier.weight(1f));TextButton(back,Modifier.fillMaxWidth()){Text("VOLVER")}}}
@Composable private fun SocialMealScreen(done:(String,Int)->Unit,back:()->Unit){var selected by remember{mutableStateOf<SocialMeal?>(null)};var amount by remember{mutableStateOf(SocialAmount.NORMAL)};Column(Modifier.padding(horizontal=22.dp)){Header("COMIDAS SOCIALES","Estimación rápida");Text("No necesitas pesar. Elige una referencia y cuánto comiste.",color=TitanTextSecondary);selected?.let{meal->Text(meal.name,fontWeight=FontWeight.Bold,fontSize=24.sp);Row{SocialAmount.entries.forEach{a->FilterChip(amount==a,{amount=a},{Text(when(a){SocialAmount.LITTLE->"POCO";SocialAmount.NORMAL->"NORMAL";SocialAmount.A_LOT->"BASTANTE"})});Spacer(Modifier.width(6.dp))}};Text("Estimación: "+MealEngine.socialKcal(meal,amount)+" kcal",color=TitanPrimary,fontWeight=FontWeight.Bold);PrimaryButton("Añadir comida social"){done(meal.name,MealEngine.socialKcal(meal,amount))}}?:run{MealEngine.socialMeals.forEach{meal->Card(onClick={selected=meal},colors=CardDefaults.cardColors(containerColor=TitanCard),modifier=Modifier.fillMaxWidth().padding(vertical=5.dp)){Text(meal.name,Modifier.padding(18.dp),fontWeight=FontWeight.SemiBold)}}};Spacer(Modifier.weight(1f));TextButton(back,Modifier.fillMaxWidth()){Text("Volver")}}}
